// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authorization.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Permission Check
type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`                                                                               // e.g., "user", "tenant", "api"
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`                                                                                   // e.g., "read", "write", "delete", "execute"
	Attributes    map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // For ABAC conditions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPermissionRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckPermissionRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CheckPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`                                    // Why allowed/denied
	MatchedPolicy string                 `protobuf:"bytes,3,opt,name=matched_policy,json=matchedPolicy,proto3" json:"matched_policy,omitempty"` // Which policy matched
	Error         *ErrorResponse         `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *CheckPermissionResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckPermissionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckPermissionResponse) GetMatchedPolicy() string {
	if x != nil {
		return x.MatchedPolicy
	}
	return ""
}

func (x *CheckPermissionResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Batch Permission Check
type CheckPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Checks        []*PermissionCheck     `protobuf:"bytes,4,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsRequest) Reset() {
	*x = CheckPermissionsRequest{}
	mi := &file_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsRequest) ProtoMessage() {}

func (x *CheckPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *CheckPermissionsRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CheckPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckPermissionsRequest) GetChecks() []*PermissionCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

type PermissionCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionCheck) Reset() {
	*x = PermissionCheck{}
	mi := &file_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionCheck) ProtoMessage() {}

func (x *PermissionCheck) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionCheck.ProtoReflect.Descriptor instead.
func (*PermissionCheck) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *PermissionCheck) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionCheck) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionCheck) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type CheckPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PermissionResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsResponse) Reset() {
	*x = CheckPermissionsResponse{}
	mi := &file_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsResponse) ProtoMessage() {}

func (x *CheckPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *CheckPermissionsResponse) GetResults() []*PermissionResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CheckPermissionsResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type PermissionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Allowed       bool                   `protobuf:"varint,3,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResult) Reset() {
	*x = PermissionResult{}
	mi := &file_authorization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResult) ProtoMessage() {}

func (x *PermissionResult) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResult.ProtoReflect.Descriptor instead.
func (*PermissionResult) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{5}
}

func (x *PermissionResult) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionResult) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionResult) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PermissionResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// User Roles
type GetUserRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesRequest) Reset() {
	*x = GetUserRolesRequest{}
	mi := &file_authorization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesRequest) ProtoMessage() {}

func (x *GetUserRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesRequest.ProtoReflect.Descriptor instead.
func (*GetUserRolesRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRolesRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetUserRolesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserRolesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetUserRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRolesResponse) Reset() {
	*x = GetUserRolesResponse{}
	mi := &file_authorization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRolesResponse) ProtoMessage() {}

func (x *GetUserRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRolesResponse.ProtoReflect.Descriptor instead.
func (*GetUserRolesResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetUserRolesResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsSystem      bool                   `protobuf:"varint,4,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	Privileges    []string               `protobuf:"bytes,5,rep,name=privileges,proto3" json:"privileges,omitempty"`
	ValidFrom     int64                  `protobuf:"varint,6,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidUntil    int64                  `protobuf:"varint,7,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_authorization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{8}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *Role) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *Role) GetValidFrom() int64 {
	if x != nil {
		return x.ValidFrom
	}
	return 0
}

func (x *Role) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

// Role Permissions
type GetRolePermissionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Context          *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	RoleId           string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	IncludeInherited bool                   `protobuf:"varint,3,opt,name=include_inherited,json=includeInherited,proto3" json:"include_inherited,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetRolePermissionsRequest) Reset() {
	*x = GetRolePermissionsRequest{}
	mi := &file_authorization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsRequest) ProtoMessage() {}

func (x *GetRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{9}
}

func (x *GetRolePermissionsRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetRolePermissionsRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *GetRolePermissionsRequest) GetIncludeInherited() bool {
	if x != nil {
		return x.IncludeInherited
	}
	return false
}

type GetRolePermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsResponse) Reset() {
	*x = GetRolePermissionsResponse{}
	mi := &file_authorization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsResponse) ProtoMessage() {}

func (x *GetRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{10}
}

func (x *GetRolePermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetRolePermissionsResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Inherited     bool                   `protobuf:"varint,5,opt,name=inherited,proto3" json:"inherited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_authorization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{11}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Permission) GetInherited() bool {
	if x != nil {
		return x.Inherited
	}
	return false
}

// Policy Evaluation
type EvaluatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PolicyId      string                 `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Input         map[string]string      `protobuf:"bytes,5,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePolicyRequest) Reset() {
	*x = EvaluatePolicyRequest{}
	mi := &file_authorization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePolicyRequest) ProtoMessage() {}

func (x *EvaluatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePolicyRequest.ProtoReflect.Descriptor instead.
func (*EvaluatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{12}
}

func (x *EvaluatePolicyRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *EvaluatePolicyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EvaluatePolicyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EvaluatePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *EvaluatePolicyRequest) GetInput() map[string]string {
	if x != nil {
		return x.Input
	}
	return nil
}

type EvaluatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Effect        string                 `protobuf:"bytes,1,opt,name=effect,proto3" json:"effect,omitempty"` // "ALLOW", "DENY", "CONDITIONAL"
	Conditions    map[string]string      `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePolicyResponse) Reset() {
	*x = EvaluatePolicyResponse{}
	mi := &file_authorization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePolicyResponse) ProtoMessage() {}

func (x *EvaluatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePolicyResponse.ProtoReflect.Descriptor instead.
func (*EvaluatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{13}
}

func (x *EvaluatePolicyResponse) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *EvaluatePolicyResponse) GetConditions() map[string]string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *EvaluatePolicyResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type CreateTenantAuthSettingRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Context                    *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TenantId                   string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EnforceMfa                 bool                   `protobuf:"varint,3,opt,name=enforce_mfa,json=enforceMfa,proto3" json:"enforce_mfa,omitempty"`
	SessionTimeoutMinutes      int32                  `protobuf:"varint,4,opt,name=session_timeout_minutes,json=sessionTimeoutMinutes,proto3" json:"session_timeout_minutes,omitempty"`
	MaxConcurrentSessions      int32                  `protobuf:"varint,5,opt,name=max_concurrent_sessions,json=maxConcurrentSessions,proto3" json:"max_concurrent_sessions,omitempty"`
	PermissionConflictStrategy string                 `protobuf:"bytes,6,opt,name=permission_conflict_strategy,json=permissionConflictStrategy,proto3" json:"permission_conflict_strategy,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CreateTenantAuthSettingRequest) Reset() {
	*x = CreateTenantAuthSettingRequest{}
	mi := &file_authorization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantAuthSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantAuthSettingRequest) ProtoMessage() {}

func (x *CreateTenantAuthSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantAuthSettingRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantAuthSettingRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTenantAuthSettingRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateTenantAuthSettingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTenantAuthSettingRequest) GetEnforceMfa() bool {
	if x != nil {
		return x.EnforceMfa
	}
	return false
}

func (x *CreateTenantAuthSettingRequest) GetSessionTimeoutMinutes() int32 {
	if x != nil {
		return x.SessionTimeoutMinutes
	}
	return 0
}

func (x *CreateTenantAuthSettingRequest) GetMaxConcurrentSessions() int32 {
	if x != nil {
		return x.MaxConcurrentSessions
	}
	return 0
}

func (x *CreateTenantAuthSettingRequest) GetPermissionConflictStrategy() string {
	if x != nil {
		return x.PermissionConflictStrategy
	}
	return ""
}

type TenantAuthSettingResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Id                         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId                   string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EnforceMfa                 bool                   `protobuf:"varint,3,opt,name=enforce_mfa,json=enforceMfa,proto3" json:"enforce_mfa,omitempty"`
	SessionTimeoutMinutes      int32                  `protobuf:"varint,4,opt,name=session_timeout_minutes,json=sessionTimeoutMinutes,proto3" json:"session_timeout_minutes,omitempty"`
	MaxConcurrentSessions      int32                  `protobuf:"varint,5,opt,name=max_concurrent_sessions,json=maxConcurrentSessions,proto3" json:"max_concurrent_sessions,omitempty"`
	PermissionConflictStrategy string                 `protobuf:"bytes,6,opt,name=permission_conflict_strategy,json=permissionConflictStrategy,proto3" json:"permission_conflict_strategy,omitempty"`
	DefaultRoleId              string                 `protobuf:"bytes,7,opt,name=default_role_id,json=defaultRoleId,proto3" json:"default_role_id,omitempty"`
	Error                      *ErrorResponse         `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TenantAuthSettingResponse) Reset() {
	*x = TenantAuthSettingResponse{}
	mi := &file_authorization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantAuthSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantAuthSettingResponse) ProtoMessage() {}

func (x *TenantAuthSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantAuthSettingResponse.ProtoReflect.Descriptor instead.
func (*TenantAuthSettingResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{15}
}

func (x *TenantAuthSettingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantAuthSettingResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantAuthSettingResponse) GetEnforceMfa() bool {
	if x != nil {
		return x.EnforceMfa
	}
	return false
}

func (x *TenantAuthSettingResponse) GetSessionTimeoutMinutes() int32 {
	if x != nil {
		return x.SessionTimeoutMinutes
	}
	return 0
}

func (x *TenantAuthSettingResponse) GetMaxConcurrentSessions() int32 {
	if x != nil {
		return x.MaxConcurrentSessions
	}
	return 0
}

func (x *TenantAuthSettingResponse) GetPermissionConflictStrategy() string {
	if x != nil {
		return x.PermissionConflictStrategy
	}
	return ""
}

func (x *TenantAuthSettingResponse) GetDefaultRoleId() string {
	if x != nil {
		return x.DefaultRoleId
	}
	return ""
}

func (x *TenantAuthSettingResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetTenantAuthSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantAuthSettingRequest) Reset() {
	*x = GetTenantAuthSettingRequest{}
	mi := &file_authorization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantAuthSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantAuthSettingRequest) ProtoMessage() {}

func (x *GetTenantAuthSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantAuthSettingRequest.ProtoReflect.Descriptor instead.
func (*GetTenantAuthSettingRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{16}
}

func (x *GetTenantAuthSettingRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetTenantAuthSettingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type UpdateTenantAuthSettingRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Context                    *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TenantId                   string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EnforceMfa                 *bool                  `protobuf:"varint,3,opt,name=enforce_mfa,json=enforceMfa,proto3,oneof" json:"enforce_mfa,omitempty"`
	SessionTimeoutMinutes      *int32                 `protobuf:"varint,4,opt,name=session_timeout_minutes,json=sessionTimeoutMinutes,proto3,oneof" json:"session_timeout_minutes,omitempty"`
	MaxConcurrentSessions      *int32                 `protobuf:"varint,5,opt,name=max_concurrent_sessions,json=maxConcurrentSessions,proto3,oneof" json:"max_concurrent_sessions,omitempty"`
	PermissionConflictStrategy *string                `protobuf:"bytes,6,opt,name=permission_conflict_strategy,json=permissionConflictStrategy,proto3,oneof" json:"permission_conflict_strategy,omitempty"`
	DefaultRoleId              *string                `protobuf:"bytes,7,opt,name=default_role_id,json=defaultRoleId,proto3,oneof" json:"default_role_id,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateTenantAuthSettingRequest) Reset() {
	*x = UpdateTenantAuthSettingRequest{}
	mi := &file_authorization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantAuthSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantAuthSettingRequest) ProtoMessage() {}

func (x *UpdateTenantAuthSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantAuthSettingRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantAuthSettingRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateTenantAuthSettingRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateTenantAuthSettingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateTenantAuthSettingRequest) GetEnforceMfa() bool {
	if x != nil && x.EnforceMfa != nil {
		return *x.EnforceMfa
	}
	return false
}

func (x *UpdateTenantAuthSettingRequest) GetSessionTimeoutMinutes() int32 {
	if x != nil && x.SessionTimeoutMinutes != nil {
		return *x.SessionTimeoutMinutes
	}
	return 0
}

func (x *UpdateTenantAuthSettingRequest) GetMaxConcurrentSessions() int32 {
	if x != nil && x.MaxConcurrentSessions != nil {
		return *x.MaxConcurrentSessions
	}
	return 0
}

func (x *UpdateTenantAuthSettingRequest) GetPermissionConflictStrategy() string {
	if x != nil && x.PermissionConflictStrategy != nil {
		return *x.PermissionConflictStrategy
	}
	return ""
}

func (x *UpdateTenantAuthSettingRequest) GetDefaultRoleId() string {
	if x != nil && x.DefaultRoleId != nil {
		return *x.DefaultRoleId
	}
	return ""
}

type DeleteTenantAuthSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantAuthSettingRequest) Reset() {
	*x = DeleteTenantAuthSettingRequest{}
	mi := &file_authorization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantAuthSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantAuthSettingRequest) ProtoMessage() {}

func (x *DeleteTenantAuthSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantAuthSettingRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantAuthSettingRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteTenantAuthSettingRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteTenantAuthSettingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Privileges    []string               `protobuf:"bytes,5,rep,name=privileges,proto3" json:"privileges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_authorization_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{19}
}

func (x *CreateRoleRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateRoleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsSystem      bool                   `protobuf:"varint,5,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	Privileges    []string               `protobuf:"bytes,6,rep,name=privileges,proto3" json:"privileges,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_authorization_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{20}
}

func (x *RoleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RoleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleResponse) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *RoleResponse) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

func (x *RoleResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Privileges    []string               `protobuf:"bytes,6,rep,name=privileges,proto3" json:"privileges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_authorization_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateRoleRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateRoleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateRoleRequest) GetPrivileges() []string {
	if x != nil {
		return x.Privileges
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_authorization_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteRoleRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRoleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_authorization_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{23}
}

func (x *AssignRoleRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignRoleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_authorization_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{24}
}

func (x *AssignRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignRoleResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type RevokeRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_authorization_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{25}
}

func (x *RevokeRoleRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RevokeRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeRoleRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RevokeRoleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type RevokeRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleResponse) Reset() {
	*x = RevokeRoleResponse{}
	mi := &file_authorization_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleResponse) ProtoMessage() {}

func (x *RevokeRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleResponse.ProtoReflect.Descriptor instead.
func (*RevokeRoleResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{26}
}

func (x *RevokeRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeRoleResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_authorization_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserPermissionsRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetUserPermissionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPermissionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetUserPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponse) Reset() {
	*x = GetUserPermissionsResponse{}
	mi := &file_authorization_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponse) ProtoMessage() {}

func (x *GetUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{28}
}

func (x *GetUserPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetUserPermissionsResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_authorization_proto protoreflect.FileDescriptor

const file_authorization_proto_rawDesc = "" +
	"\n" +
	"\x13authorization.proto\x12\rauthorization\x1a\fcommon.proto\"\xca\x02\n" +
	"\x16CheckPermissionRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12U\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v25.authorization.CheckPermissionRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x17CheckPermissionResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12%\n" +
	"\x0ematched_policy\x18\x03 \x01(\tR\rmatchedPolicy\x12+\n" +
	"\x05error\x18\x04 \x01(\v2\x15.common.ErrorResponseR\x05error\"\xb9\x01\n" +
	"\x17CheckPermissionsRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x126\n" +
	"\x06checks\x18\x04 \x03(\v2\x1e.authorization.PermissionCheckR\x06checks\"\xd4\x01\n" +
	"\x0fPermissionCheck\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12N\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2..authorization.PermissionCheck.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x18CheckPermissionsResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.authorization.PermissionResultR\aresults\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"x\n" +
	"\x10PermissionResult\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\aallowed\x18\x03 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"}\n" +
	"\x13GetUserRolesRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"n\n" +
	"\x14GetUserRolesResponse\x12)\n" +
	"\x05roles\x18\x01 \x03(\v2\x13.authorization.RoleR\x05roles\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"\xc9\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_system\x18\x04 \x01(\bR\bisSystem\x12\x1e\n" +
	"\n" +
	"privileges\x18\x05 \x03(\tR\n" +
	"privileges\x12\x1d\n" +
	"\n" +
	"valid_from\x18\x06 \x01(\x03R\tvalidFrom\x12\x1f\n" +
	"\vvalid_until\x18\a \x01(\x03R\n" +
	"validUntil\"\x93\x01\n" +
	"\x19GetRolePermissionsRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12+\n" +
	"\x11include_inherited\x18\x03 \x01(\bR\x10includeInherited\"\x86\x01\n" +
	"\x1aGetRolePermissionsResponse\x12;\n" +
	"\vpermissions\x18\x01 \x03(\v2\x19.authorization.PermissionR\vpermissions\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"\x82\x01\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1c\n" +
	"\tinherited\x18\x05 \x01(\bR\tinherited\"\x9d\x02\n" +
	"\x15EvaluatePolicyRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpolicy_id\x18\x04 \x01(\tR\bpolicyId\x12E\n" +
	"\x05input\x18\x05 \x03(\v2/.authorization.EvaluatePolicyRequest.InputEntryR\x05input\x1a8\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x16EvaluatePolicyResponse\x12\x16\n" +
	"\x06effect\x18\x01 \x01(\tR\x06effect\x12U\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v25.authorization.EvaluatePolicyResponse.ConditionsEntryR\n" +
	"conditions\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error\x1a=\n" +
	"\x0fConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x02\n" +
	"\x1eCreateTenantAuthSettingRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\venforce_mfa\x18\x03 \x01(\bR\n" +
	"enforceMfa\x126\n" +
	"\x17session_timeout_minutes\x18\x04 \x01(\x05R\x15sessionTimeoutMinutes\x126\n" +
	"\x17max_concurrent_sessions\x18\x05 \x01(\x05R\x15maxConcurrentSessions\x12@\n" +
	"\x1cpermission_conflict_strategy\x18\x06 \x01(\tR\x1apermissionConflictStrategy\"\xf0\x02\n" +
	"\x19TenantAuthSettingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\venforce_mfa\x18\x03 \x01(\bR\n" +
	"enforceMfa\x126\n" +
	"\x17session_timeout_minutes\x18\x04 \x01(\x05R\x15sessionTimeoutMinutes\x126\n" +
	"\x17max_concurrent_sessions\x18\x05 \x01(\x05R\x15maxConcurrentSessions\x12@\n" +
	"\x1cpermission_conflict_strategy\x18\x06 \x01(\tR\x1apermissionConflictStrategy\x12&\n" +
	"\x0fdefault_role_id\x18\a \x01(\tR\rdefaultRoleId\x12+\n" +
	"\x05error\x18\b \x01(\v2\x15.common.ErrorResponseR\x05error\"l\n" +
	"\x1bGetTenantAuthSettingRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\x80\x04\n" +
	"\x1eUpdateTenantAuthSettingRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12$\n" +
	"\venforce_mfa\x18\x03 \x01(\bH\x00R\n" +
	"enforceMfa\x88\x01\x01\x12;\n" +
	"\x17session_timeout_minutes\x18\x04 \x01(\x05H\x01R\x15sessionTimeoutMinutes\x88\x01\x01\x12;\n" +
	"\x17max_concurrent_sessions\x18\x05 \x01(\x05H\x02R\x15maxConcurrentSessions\x88\x01\x01\x12E\n" +
	"\x1cpermission_conflict_strategy\x18\x06 \x01(\tH\x03R\x1apermissionConflictStrategy\x88\x01\x01\x12+\n" +
	"\x0fdefault_role_id\x18\a \x01(\tH\x04R\rdefaultRoleId\x88\x01\x01B\x0e\n" +
	"\f_enforce_mfaB\x1a\n" +
	"\x18_session_timeout_minutesB\x1a\n" +
	"\x18_max_concurrent_sessionsB\x1f\n" +
	"\x1d_permission_conflict_strategyB\x12\n" +
	"\x10_default_role_id\"o\n" +
	"\x1eDeleteTenantAuthSettingRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"\xb8\x01\n" +
	"\x11CreateRoleRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"privileges\x18\x05 \x03(\tR\n" +
	"privileges\"\xdb\x01\n" +
	"\fRoleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_system\x18\x05 \x01(\bR\bisSystem\x12\x1e\n" +
	"\n" +
	"privileges\x18\x06 \x03(\tR\n" +
	"privileges\x12+\n" +
	"\x05error\x18\a \x01(\v2\x15.common.ErrorResponseR\x05error\"\xeb\x01\n" +
	"\x11UpdateRoleRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"privileges\x18\x06 \x03(\tR\n" +
	"privilegesB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"r\n" +
	"\x11DeleteRoleRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\x94\x01\n" +
	"\x11AssignRoleRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"[\n" +
	"\x12AssignRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"\x94\x01\n" +
	"\x11RevokeRoleRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"[\n" +
	"\x12RevokeRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error\"\x83\x01\n" +
	"\x19GetUserPermissionsRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\x86\x01\n" +
	"\x1aGetUserPermissionsResponse\x12;\n" +
	"\vpermissions\x18\x01 \x03(\v2\x19.authorization.PermissionR\vpermissions\x12+\n" +
	"\x05error\x18\x02 \x01(\v2\x15.common.ErrorResponseR\x05error2\xb9\v\n" +
	"\x14AuthorizationService\x12`\n" +
	"\x0fCheckPermission\x12%.authorization.CheckPermissionRequest\x1a&.authorization.CheckPermissionResponse\x12c\n" +
	"\x10CheckPermissions\x12&.authorization.CheckPermissionsRequest\x1a'.authorization.CheckPermissionsResponse\x12W\n" +
	"\fGetUserRoles\x12\".authorization.GetUserRolesRequest\x1a#.authorization.GetUserRolesResponse\x12i\n" +
	"\x12GetRolePermissions\x12(.authorization.GetRolePermissionsRequest\x1a).authorization.GetRolePermissionsResponse\x12]\n" +
	"\x0eEvaluatePolicy\x12$.authorization.EvaluatePolicyRequest\x1a%.authorization.EvaluatePolicyResponse\x12r\n" +
	"\x17CreateTenantAuthSetting\x12-.authorization.CreateTenantAuthSettingRequest\x1a(.authorization.TenantAuthSettingResponse\x12l\n" +
	"\x14GetTenantAuthSetting\x12*.authorization.GetTenantAuthSettingRequest\x1a(.authorization.TenantAuthSettingResponse\x12r\n" +
	"\x17UpdateTenantAuthSetting\x12-.authorization.UpdateTenantAuthSettingRequest\x1a(.authorization.TenantAuthSettingResponse\x12`\n" +
	"\x17DeleteTenantAuthSetting\x12-.authorization.DeleteTenantAuthSettingRequest\x1a\x16.common.DeleteResponse\x12K\n" +
	"\n" +
	"CreateRole\x12 .authorization.CreateRoleRequest\x1a\x1b.authorization.RoleResponse\x12K\n" +
	"\n" +
	"UpdateRole\x12 .authorization.UpdateRoleRequest\x1a\x1b.authorization.RoleResponse\x12F\n" +
	"\n" +
	"DeleteRole\x12 .authorization.DeleteRoleRequest\x1a\x16.common.DeleteResponse\x12W\n" +
	"\x10AssignRoleToUser\x12 .authorization.AssignRoleRequest\x1a!.authorization.AssignRoleResponse\x12Y\n" +
	"\x12RevokeRoleFromUser\x12 .authorization.RevokeRoleRequest\x1a!.authorization.RevokeRoleResponse\x12i\n" +
	"\x12GetUserPermissions\x12(.authorization.GetUserPermissionsRequest\x1a).authorization.GetUserPermissionsResponseB\x9c\x01\n" +
	"\x11com.authorizationB\x12AuthorizationProtoP\x01Z\x1fgithub.com/yourorg/sdk/go/proto\xa2\x02\x03AXX\xaa\x02\rAuthorization\xca\x02\rAuthorization\xe2\x02\x19Authorization\\GPBMetadata\xea\x02\rAuthorizationb\x06proto3"

var (
	file_authorization_proto_rawDescOnce sync.Once
	file_authorization_proto_rawDescData []byte
)

func file_authorization_proto_rawDescGZIP() []byte {
	file_authorization_proto_rawDescOnce.Do(func() {
		file_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authorization_proto_rawDesc), len(file_authorization_proto_rawDesc)))
	})
	return file_authorization_proto_rawDescData
}

var file_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_authorization_proto_goTypes = []any{
	(*CheckPermissionRequest)(nil),         // 0: authorization.CheckPermissionRequest
	(*CheckPermissionResponse)(nil),        // 1: authorization.CheckPermissionResponse
	(*CheckPermissionsRequest)(nil),        // 2: authorization.CheckPermissionsRequest
	(*PermissionCheck)(nil),                // 3: authorization.PermissionCheck
	(*CheckPermissionsResponse)(nil),       // 4: authorization.CheckPermissionsResponse
	(*PermissionResult)(nil),               // 5: authorization.PermissionResult
	(*GetUserRolesRequest)(nil),            // 6: authorization.GetUserRolesRequest
	(*GetUserRolesResponse)(nil),           // 7: authorization.GetUserRolesResponse
	(*Role)(nil),                           // 8: authorization.Role
	(*GetRolePermissionsRequest)(nil),      // 9: authorization.GetRolePermissionsRequest
	(*GetRolePermissionsResponse)(nil),     // 10: authorization.GetRolePermissionsResponse
	(*Permission)(nil),                     // 11: authorization.Permission
	(*EvaluatePolicyRequest)(nil),          // 12: authorization.EvaluatePolicyRequest
	(*EvaluatePolicyResponse)(nil),         // 13: authorization.EvaluatePolicyResponse
	(*CreateTenantAuthSettingRequest)(nil), // 14: authorization.CreateTenantAuthSettingRequest
	(*TenantAuthSettingResponse)(nil),      // 15: authorization.TenantAuthSettingResponse
	(*GetTenantAuthSettingRequest)(nil),    // 16: authorization.GetTenantAuthSettingRequest
	(*UpdateTenantAuthSettingRequest)(nil), // 17: authorization.UpdateTenantAuthSettingRequest
	(*DeleteTenantAuthSettingRequest)(nil), // 18: authorization.DeleteTenantAuthSettingRequest
	(*CreateRoleRequest)(nil),              // 19: authorization.CreateRoleRequest
	(*RoleResponse)(nil),                   // 20: authorization.RoleResponse
	(*UpdateRoleRequest)(nil),              // 21: authorization.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),              // 22: authorization.DeleteRoleRequest
	(*AssignRoleRequest)(nil),              // 23: authorization.AssignRoleRequest
	(*AssignRoleResponse)(nil),             // 24: authorization.AssignRoleResponse
	(*RevokeRoleRequest)(nil),              // 25: authorization.RevokeRoleRequest
	(*RevokeRoleResponse)(nil),             // 26: authorization.RevokeRoleResponse
	(*GetUserPermissionsRequest)(nil),      // 27: authorization.GetUserPermissionsRequest
	(*GetUserPermissionsResponse)(nil),     // 28: authorization.GetUserPermissionsResponse
	nil,                                    // 29: authorization.CheckPermissionRequest.AttributesEntry
	nil,                                    // 30: authorization.PermissionCheck.AttributesEntry
	nil,                                    // 31: authorization.EvaluatePolicyRequest.InputEntry
	nil,                                    // 32: authorization.EvaluatePolicyResponse.ConditionsEntry
	(*RequestContext)(nil),                 // 33: common.RequestContext
	(*ErrorResponse)(nil),                  // 34: common.ErrorResponse
	(*DeleteResponse)(nil),                 // 35: common.DeleteResponse
}
var file_authorization_proto_depIdxs = []int32{
	33, // 0: authorization.CheckPermissionRequest.context:type_name -> common.RequestContext
	29, // 1: authorization.CheckPermissionRequest.attributes:type_name -> authorization.CheckPermissionRequest.AttributesEntry
	34, // 2: authorization.CheckPermissionResponse.error:type_name -> common.ErrorResponse
	33, // 3: authorization.CheckPermissionsRequest.context:type_name -> common.RequestContext
	3,  // 4: authorization.CheckPermissionsRequest.checks:type_name -> authorization.PermissionCheck
	30, // 5: authorization.PermissionCheck.attributes:type_name -> authorization.PermissionCheck.AttributesEntry
	5,  // 6: authorization.CheckPermissionsResponse.results:type_name -> authorization.PermissionResult
	34, // 7: authorization.CheckPermissionsResponse.error:type_name -> common.ErrorResponse
	33, // 8: authorization.GetUserRolesRequest.context:type_name -> common.RequestContext
	8,  // 9: authorization.GetUserRolesResponse.roles:type_name -> authorization.Role
	34, // 10: authorization.GetUserRolesResponse.error:type_name -> common.ErrorResponse
	33, // 11: authorization.GetRolePermissionsRequest.context:type_name -> common.RequestContext
	11, // 12: authorization.GetRolePermissionsResponse.permissions:type_name -> authorization.Permission
	34, // 13: authorization.GetRolePermissionsResponse.error:type_name -> common.ErrorResponse
	33, // 14: authorization.EvaluatePolicyRequest.context:type_name -> common.RequestContext
	31, // 15: authorization.EvaluatePolicyRequest.input:type_name -> authorization.EvaluatePolicyRequest.InputEntry
	32, // 16: authorization.EvaluatePolicyResponse.conditions:type_name -> authorization.EvaluatePolicyResponse.ConditionsEntry
	34, // 17: authorization.EvaluatePolicyResponse.error:type_name -> common.ErrorResponse
	33, // 18: authorization.CreateTenantAuthSettingRequest.context:type_name -> common.RequestContext
	34, // 19: authorization.TenantAuthSettingResponse.error:type_name -> common.ErrorResponse
	33, // 20: authorization.GetTenantAuthSettingRequest.context:type_name -> common.RequestContext
	33, // 21: authorization.UpdateTenantAuthSettingRequest.context:type_name -> common.RequestContext
	33, // 22: authorization.DeleteTenantAuthSettingRequest.context:type_name -> common.RequestContext
	33, // 23: authorization.CreateRoleRequest.context:type_name -> common.RequestContext
	34, // 24: authorization.RoleResponse.error:type_name -> common.ErrorResponse
	33, // 25: authorization.UpdateRoleRequest.context:type_name -> common.RequestContext
	33, // 26: authorization.DeleteRoleRequest.context:type_name -> common.RequestContext
	33, // 27: authorization.AssignRoleRequest.context:type_name -> common.RequestContext
	34, // 28: authorization.AssignRoleResponse.error:type_name -> common.ErrorResponse
	33, // 29: authorization.RevokeRoleRequest.context:type_name -> common.RequestContext
	34, // 30: authorization.RevokeRoleResponse.error:type_name -> common.ErrorResponse
	33, // 31: authorization.GetUserPermissionsRequest.context:type_name -> common.RequestContext
	11, // 32: authorization.GetUserPermissionsResponse.permissions:type_name -> authorization.Permission
	34, // 33: authorization.GetUserPermissionsResponse.error:type_name -> common.ErrorResponse
	0,  // 34: authorization.AuthorizationService.CheckPermission:input_type -> authorization.CheckPermissionRequest
	2,  // 35: authorization.AuthorizationService.CheckPermissions:input_type -> authorization.CheckPermissionsRequest
	6,  // 36: authorization.AuthorizationService.GetUserRoles:input_type -> authorization.GetUserRolesRequest
	9,  // 37: authorization.AuthorizationService.GetRolePermissions:input_type -> authorization.GetRolePermissionsRequest
	12, // 38: authorization.AuthorizationService.EvaluatePolicy:input_type -> authorization.EvaluatePolicyRequest
	14, // 39: authorization.AuthorizationService.CreateTenantAuthSetting:input_type -> authorization.CreateTenantAuthSettingRequest
	16, // 40: authorization.AuthorizationService.GetTenantAuthSetting:input_type -> authorization.GetTenantAuthSettingRequest
	17, // 41: authorization.AuthorizationService.UpdateTenantAuthSetting:input_type -> authorization.UpdateTenantAuthSettingRequest
	18, // 42: authorization.AuthorizationService.DeleteTenantAuthSetting:input_type -> authorization.DeleteTenantAuthSettingRequest
	19, // 43: authorization.AuthorizationService.CreateRole:input_type -> authorization.CreateRoleRequest
	21, // 44: authorization.AuthorizationService.UpdateRole:input_type -> authorization.UpdateRoleRequest
	22, // 45: authorization.AuthorizationService.DeleteRole:input_type -> authorization.DeleteRoleRequest
	23, // 46: authorization.AuthorizationService.AssignRoleToUser:input_type -> authorization.AssignRoleRequest
	25, // 47: authorization.AuthorizationService.RevokeRoleFromUser:input_type -> authorization.RevokeRoleRequest
	27, // 48: authorization.AuthorizationService.GetUserPermissions:input_type -> authorization.GetUserPermissionsRequest
	1,  // 49: authorization.AuthorizationService.CheckPermission:output_type -> authorization.CheckPermissionResponse
	4,  // 50: authorization.AuthorizationService.CheckPermissions:output_type -> authorization.CheckPermissionsResponse
	7,  // 51: authorization.AuthorizationService.GetUserRoles:output_type -> authorization.GetUserRolesResponse
	10, // 52: authorization.AuthorizationService.GetRolePermissions:output_type -> authorization.GetRolePermissionsResponse
	13, // 53: authorization.AuthorizationService.EvaluatePolicy:output_type -> authorization.EvaluatePolicyResponse
	15, // 54: authorization.AuthorizationService.CreateTenantAuthSetting:output_type -> authorization.TenantAuthSettingResponse
	15, // 55: authorization.AuthorizationService.GetTenantAuthSetting:output_type -> authorization.TenantAuthSettingResponse
	15, // 56: authorization.AuthorizationService.UpdateTenantAuthSetting:output_type -> authorization.TenantAuthSettingResponse
	35, // 57: authorization.AuthorizationService.DeleteTenantAuthSetting:output_type -> common.DeleteResponse
	20, // 58: authorization.AuthorizationService.CreateRole:output_type -> authorization.RoleResponse
	20, // 59: authorization.AuthorizationService.UpdateRole:output_type -> authorization.RoleResponse
	35, // 60: authorization.AuthorizationService.DeleteRole:output_type -> common.DeleteResponse
	24, // 61: authorization.AuthorizationService.AssignRoleToUser:output_type -> authorization.AssignRoleResponse
	26, // 62: authorization.AuthorizationService.RevokeRoleFromUser:output_type -> authorization.RevokeRoleResponse
	28, // 63: authorization.AuthorizationService.GetUserPermissions:output_type -> authorization.GetUserPermissionsResponse
	49, // [49:64] is the sub-list for method output_type
	34, // [34:49] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_authorization_proto_init() }
func file_authorization_proto_init() {
	if File_authorization_proto != nil {
		return
	}
	file_common_proto_init()
	file_authorization_proto_msgTypes[17].OneofWrappers = []any{}
	file_authorization_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authorization_proto_rawDesc), len(file_authorization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authorization_proto_goTypes,
		DependencyIndexes: file_authorization_proto_depIdxs,
		MessageInfos:      file_authorization_proto_msgTypes,
	}.Build()
	File_authorization_proto = out.File
	file_authorization_proto_goTypes = nil
	file_authorization_proto_depIdxs = nil
}
