// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: control-plane.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get Policy Manifest
type GetPolicyManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // Optional specific version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyManifestRequest) Reset() {
	*x = GetPolicyManifestRequest{}
	mi := &file_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyManifestRequest) ProtoMessage() {}

func (x *GetPolicyManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyManifestRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyManifestRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *GetPolicyManifestRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetPolicyManifestRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetPolicyManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Manifest      *PolicyManifest        `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyManifestResponse) Reset() {
	*x = GetPolicyManifestResponse{}
	mi := &file_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyManifestResponse) ProtoMessage() {}

func (x *GetPolicyManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyManifestResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyManifestResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *GetPolicyManifestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPolicyManifestResponse) GetManifest() *PolicyManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *GetPolicyManifestResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type PolicyManifest struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Version          string                     `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp        int64                      `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Routes           []*RoutePolicyManifest     `protobuf:"bytes,3,rep,name=routes,proto3" json:"routes,omitempty"`
	Tiers            []*CapabilityTierManifest  `protobuf:"bytes,4,rep,name=tiers,proto3" json:"tiers,omitempty"`
	FailurePolicies  []*FailurePolicyManifest   `protobuf:"bytes,5,rep,name=failurePolicies,proto3" json:"failurePolicies,omitempty"`
	TemporalRules    []*TemporalRuleManifest    `protobuf:"bytes,6,rep,name=temporalRules,proto3" json:"temporalRules,omitempty"`
	EnvironmentRules []*EnvironmentRuleManifest `protobuf:"bytes,7,rep,name=environmentRules,proto3" json:"environmentRules,omitempty"`
	UpgradePipelines []*UpgradePipelineManifest `protobuf:"bytes,8,rep,name=upgradePipelines,proto3" json:"upgradePipelines,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PolicyManifest) Reset() {
	*x = PolicyManifest{}
	mi := &file_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyManifest) ProtoMessage() {}

func (x *PolicyManifest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyManifest.ProtoReflect.Descriptor instead.
func (*PolicyManifest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PolicyManifest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PolicyManifest) GetRoutes() []*RoutePolicyManifest {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *PolicyManifest) GetTiers() []*CapabilityTierManifest {
	if x != nil {
		return x.Tiers
	}
	return nil
}

func (x *PolicyManifest) GetFailurePolicies() []*FailurePolicyManifest {
	if x != nil {
		return x.FailurePolicies
	}
	return nil
}

func (x *PolicyManifest) GetTemporalRules() []*TemporalRuleManifest {
	if x != nil {
		return x.TemporalRules
	}
	return nil
}

func (x *PolicyManifest) GetEnvironmentRules() []*EnvironmentRuleManifest {
	if x != nil {
		return x.EnvironmentRules
	}
	return nil
}

func (x *PolicyManifest) GetUpgradePipelines() []*UpgradePipelineManifest {
	if x != nil {
		return x.UpgradePipelines
	}
	return nil
}

type RoutePolicyManifest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RoutePattern           string                 `protobuf:"bytes,1,opt,name=routePattern,proto3" json:"routePattern,omitempty"`
	Semantics              string                 `protobuf:"bytes,2,opt,name=semantics,proto3" json:"semantics,omitempty"`
	RequiredCapabilityTier string                 `protobuf:"bytes,3,opt,name=requiredCapabilityTier,proto3" json:"requiredCapabilityTier,omitempty"`
	IntentClass            string                 `protobuf:"bytes,4,opt,name=intentClass,proto3" json:"intentClass,omitempty"`
	AuthRequired           bool                   `protobuf:"varint,5,opt,name=authRequired,proto3" json:"authRequired,omitempty"`
	TenantScopeRequired    bool                   `protobuf:"varint,6,opt,name=tenantScopeRequired,proto3" json:"tenantScopeRequired,omitempty"`
	TemporalRuleId         string                 `protobuf:"bytes,7,opt,name=temporalRuleId,proto3" json:"temporalRuleId,omitempty"`
	FailurePolicyId        string                 `protobuf:"bytes,8,opt,name=failurePolicyId,proto3" json:"failurePolicyId,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RoutePolicyManifest) Reset() {
	*x = RoutePolicyManifest{}
	mi := &file_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicyManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicyManifest) ProtoMessage() {}

func (x *RoutePolicyManifest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicyManifest.ProtoReflect.Descriptor instead.
func (*RoutePolicyManifest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *RoutePolicyManifest) GetRoutePattern() string {
	if x != nil {
		return x.RoutePattern
	}
	return ""
}

func (x *RoutePolicyManifest) GetSemantics() string {
	if x != nil {
		return x.Semantics
	}
	return ""
}

func (x *RoutePolicyManifest) GetRequiredCapabilityTier() string {
	if x != nil {
		return x.RequiredCapabilityTier
	}
	return ""
}

func (x *RoutePolicyManifest) GetIntentClass() string {
	if x != nil {
		return x.IntentClass
	}
	return ""
}

func (x *RoutePolicyManifest) GetAuthRequired() bool {
	if x != nil {
		return x.AuthRequired
	}
	return false
}

func (x *RoutePolicyManifest) GetTenantScopeRequired() bool {
	if x != nil {
		return x.TenantScopeRequired
	}
	return false
}

func (x *RoutePolicyManifest) GetTemporalRuleId() string {
	if x != nil {
		return x.TemporalRuleId
	}
	return ""
}

func (x *RoutePolicyManifest) GetFailurePolicyId() string {
	if x != nil {
		return x.FailurePolicyId
	}
	return ""
}

type CapabilityTierManifest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TierType           string                 `protobuf:"bytes,2,opt,name=tierType,proto3" json:"tierType,omitempty"`
	Order              int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	UpgradePathIds     []string               `protobuf:"bytes,4,rep,name=upgradePathIds,proto3" json:"upgradePathIds,omitempty"`
	ExpirationDefaults map[string]string      `protobuf:"bytes,5,rep,name=expirationDefaults,proto3" json:"expirationDefaults,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Permissions        map[string]string      `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CapabilityTierManifest) Reset() {
	*x = CapabilityTierManifest{}
	mi := &file_control_plane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityTierManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityTierManifest) ProtoMessage() {}

func (x *CapabilityTierManifest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityTierManifest.ProtoReflect.Descriptor instead.
func (*CapabilityTierManifest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityTierManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapabilityTierManifest) GetTierType() string {
	if x != nil {
		return x.TierType
	}
	return ""
}

func (x *CapabilityTierManifest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *CapabilityTierManifest) GetUpgradePathIds() []string {
	if x != nil {
		return x.UpgradePathIds
	}
	return nil
}

func (x *CapabilityTierManifest) GetExpirationDefaults() map[string]string {
	if x != nil {
		return x.ExpirationDefaults
	}
	return nil
}

func (x *CapabilityTierManifest) GetPermissions() map[string]string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type FailurePolicyManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BehaviorType  string                 `protobuf:"bytes,2,opt,name=behaviorType,proto3" json:"behaviorType,omitempty"`
	Configuration map[string]string      `protobuf:"bytes,3,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailurePolicyManifest) Reset() {
	*x = FailurePolicyManifest{}
	mi := &file_control_plane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailurePolicyManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailurePolicyManifest) ProtoMessage() {}

func (x *FailurePolicyManifest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailurePolicyManifest.ProtoReflect.Descriptor instead.
func (*FailurePolicyManifest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{5}
}

func (x *FailurePolicyManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FailurePolicyManifest) GetBehaviorType() string {
	if x != nil {
		return x.BehaviorType
	}
	return ""
}

func (x *FailurePolicyManifest) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type TemporalRuleManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RuleType      string                 `protobuf:"bytes,3,opt,name=ruleType,proto3" json:"ruleType,omitempty"`
	Configuration map[string]string      `protobuf:"bytes,4,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalRuleManifest) Reset() {
	*x = TemporalRuleManifest{}
	mi := &file_control_plane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalRuleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalRuleManifest) ProtoMessage() {}

func (x *TemporalRuleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalRuleManifest.ProtoReflect.Descriptor instead.
func (*TemporalRuleManifest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{6}
}

func (x *TemporalRuleManifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemporalRuleManifest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemporalRuleManifest) GetRuleType() string {
	if x != nil {
		return x.RuleType
	}
	return ""
}

func (x *TemporalRuleManifest) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type EnvironmentRuleManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	RoutePattern  string                 `protobuf:"bytes,2,opt,name=routePattern,proto3" json:"routePattern,omitempty"`
	Overrides     map[string]string      `protobuf:"bytes,3,rep,name=overrides,proto3" json:"overrides,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentRuleManifest) Reset() {
	*x = EnvironmentRuleManifest{}
	mi := &file_control_plane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentRuleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentRuleManifest) ProtoMessage() {}

func (x *EnvironmentRuleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentRuleManifest.ProtoReflect.Descriptor instead.
func (*EnvironmentRuleManifest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{7}
}

func (x *EnvironmentRuleManifest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *EnvironmentRuleManifest) GetRoutePattern() string {
	if x != nil {
		return x.RoutePattern
	}
	return ""
}

func (x *EnvironmentRuleManifest) GetOverrides() map[string]string {
	if x != nil {
		return x.Overrides
	}
	return nil
}

type UpgradePipelineManifest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	FromTier               string                 `protobuf:"bytes,1,opt,name=fromTier,proto3" json:"fromTier,omitempty"`
	ToTier                 string                 `protobuf:"bytes,2,opt,name=toTier,proto3" json:"toTier,omitempty"`
	PreservedData          map[string]string      `protobuf:"bytes,3,rep,name=preservedData,proto3" json:"preservedData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OwnershipTransferRules map[string]string      `protobuf:"bytes,4,rep,name=ownershipTransferRules,proto3" json:"ownershipTransferRules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionUpgradeBehavior string                 `protobuf:"bytes,5,opt,name=sessionUpgradeBehavior,proto3" json:"sessionUpgradeBehavior,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpgradePipelineManifest) Reset() {
	*x = UpgradePipelineManifest{}
	mi := &file_control_plane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradePipelineManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePipelineManifest) ProtoMessage() {}

func (x *UpgradePipelineManifest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePipelineManifest.ProtoReflect.Descriptor instead.
func (*UpgradePipelineManifest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{8}
}

func (x *UpgradePipelineManifest) GetFromTier() string {
	if x != nil {
		return x.FromTier
	}
	return ""
}

func (x *UpgradePipelineManifest) GetToTier() string {
	if x != nil {
		return x.ToTier
	}
	return ""
}

func (x *UpgradePipelineManifest) GetPreservedData() map[string]string {
	if x != nil {
		return x.PreservedData
	}
	return nil
}

func (x *UpgradePipelineManifest) GetOwnershipTransferRules() map[string]string {
	if x != nil {
		return x.OwnershipTransferRules
	}
	return nil
}

func (x *UpgradePipelineManifest) GetSessionUpgradeBehavior() string {
	if x != nil {
		return x.SessionUpgradeBehavior
	}
	return ""
}

// Create Capability Tier
type CreateCapabilityTierRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Context            *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TierType           string                 `protobuf:"bytes,4,opt,name=tierType,proto3" json:"tierType,omitempty"`
	Order              int32                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	UpgradePathIds     []string               `protobuf:"bytes,6,rep,name=upgradePathIds,proto3" json:"upgradePathIds,omitempty"`
	ExpirationDefaults map[string]string      `protobuf:"bytes,7,rep,name=expirationDefaults,proto3" json:"expirationDefaults,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Permissions        map[string]string      `protobuf:"bytes,8,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsActive           bool                   `protobuf:"varint,9,opt,name=isActive,proto3" json:"isActive,omitempty"`
	TenantId           string                 `protobuf:"bytes,10,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateCapabilityTierRequest) Reset() {
	*x = CreateCapabilityTierRequest{}
	mi := &file_control_plane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCapabilityTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCapabilityTierRequest) ProtoMessage() {}

func (x *CreateCapabilityTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCapabilityTierRequest.ProtoReflect.Descriptor instead.
func (*CreateCapabilityTierRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCapabilityTierRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateCapabilityTierRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCapabilityTierRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCapabilityTierRequest) GetTierType() string {
	if x != nil {
		return x.TierType
	}
	return ""
}

func (x *CreateCapabilityTierRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *CreateCapabilityTierRequest) GetUpgradePathIds() []string {
	if x != nil {
		return x.UpgradePathIds
	}
	return nil
}

func (x *CreateCapabilityTierRequest) GetExpirationDefaults() map[string]string {
	if x != nil {
		return x.ExpirationDefaults
	}
	return nil
}

func (x *CreateCapabilityTierRequest) GetPermissions() map[string]string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CreateCapabilityTierRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateCapabilityTierRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CreateCapabilityTierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Tier          *CapabilityTier        `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCapabilityTierResponse) Reset() {
	*x = CreateCapabilityTierResponse{}
	mi := &file_control_plane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCapabilityTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCapabilityTierResponse) ProtoMessage() {}

func (x *CreateCapabilityTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCapabilityTierResponse.ProtoReflect.Descriptor instead.
func (*CreateCapabilityTierResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCapabilityTierResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCapabilityTierResponse) GetTier() *CapabilityTier {
	if x != nil {
		return x.Tier
	}
	return nil
}

func (x *CreateCapabilityTierResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type CapabilityTier struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TierType           string                 `protobuf:"bytes,5,opt,name=tierType,proto3" json:"tierType,omitempty"`
	Order              int32                  `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	UpgradePathIds     []string               `protobuf:"bytes,7,rep,name=upgradePathIds,proto3" json:"upgradePathIds,omitempty"`
	ExpirationDefaults map[string]string      `protobuf:"bytes,8,rep,name=expirationDefaults,proto3" json:"expirationDefaults,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Permissions        map[string]string      `protobuf:"bytes,9,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsActive           bool                   `protobuf:"varint,10,opt,name=isActive,proto3" json:"isActive,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt          int64                  `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CapabilityTier) Reset() {
	*x = CapabilityTier{}
	mi := &file_control_plane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityTier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityTier) ProtoMessage() {}

func (x *CapabilityTier) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityTier.ProtoReflect.Descriptor instead.
func (*CapabilityTier) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{11}
}

func (x *CapabilityTier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapabilityTier) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CapabilityTier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapabilityTier) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CapabilityTier) GetTierType() string {
	if x != nil {
		return x.TierType
	}
	return ""
}

func (x *CapabilityTier) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *CapabilityTier) GetUpgradePathIds() []string {
	if x != nil {
		return x.UpgradePathIds
	}
	return nil
}

func (x *CapabilityTier) GetExpirationDefaults() map[string]string {
	if x != nil {
		return x.ExpirationDefaults
	}
	return nil
}

func (x *CapabilityTier) GetPermissions() map[string]string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CapabilityTier) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CapabilityTier) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CapabilityTier) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Update Route Policy
type UpdateRoutePolicyRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Context                *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	PolicyId               string                 `protobuf:"bytes,2,opt,name=policyId,proto3" json:"policyId,omitempty"`
	RoutePattern           string                 `protobuf:"bytes,3,opt,name=routePattern,proto3" json:"routePattern,omitempty"`
	Semantics              string                 `protobuf:"bytes,4,opt,name=semantics,proto3" json:"semantics,omitempty"`
	RequiredCapabilityTier string                 `protobuf:"bytes,5,opt,name=requiredCapabilityTier,proto3" json:"requiredCapabilityTier,omitempty"`
	IntentClass            string                 `protobuf:"bytes,6,opt,name=intentClass,proto3" json:"intentClass,omitempty"`
	AuthRequired           bool                   `protobuf:"varint,7,opt,name=authRequired,proto3" json:"authRequired,omitempty"`
	TenantScopeRequired    bool                   `protobuf:"varint,8,opt,name=tenantScopeRequired,proto3" json:"tenantScopeRequired,omitempty"`
	TemporalRuleId         string                 `protobuf:"bytes,9,opt,name=temporalRuleId,proto3" json:"temporalRuleId,omitempty"`
	FailurePolicyId        string                 `protobuf:"bytes,10,opt,name=failurePolicyId,proto3" json:"failurePolicyId,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateRoutePolicyRequest) Reset() {
	*x = UpdateRoutePolicyRequest{}
	mi := &file_control_plane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoutePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutePolicyRequest) ProtoMessage() {}

func (x *UpdateRoutePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoutePolicyRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRoutePolicyRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateRoutePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UpdateRoutePolicyRequest) GetRoutePattern() string {
	if x != nil {
		return x.RoutePattern
	}
	return ""
}

func (x *UpdateRoutePolicyRequest) GetSemantics() string {
	if x != nil {
		return x.Semantics
	}
	return ""
}

func (x *UpdateRoutePolicyRequest) GetRequiredCapabilityTier() string {
	if x != nil {
		return x.RequiredCapabilityTier
	}
	return ""
}

func (x *UpdateRoutePolicyRequest) GetIntentClass() string {
	if x != nil {
		return x.IntentClass
	}
	return ""
}

func (x *UpdateRoutePolicyRequest) GetAuthRequired() bool {
	if x != nil {
		return x.AuthRequired
	}
	return false
}

func (x *UpdateRoutePolicyRequest) GetTenantScopeRequired() bool {
	if x != nil {
		return x.TenantScopeRequired
	}
	return false
}

func (x *UpdateRoutePolicyRequest) GetTemporalRuleId() string {
	if x != nil {
		return x.TemporalRuleId
	}
	return ""
}

func (x *UpdateRoutePolicyRequest) GetFailurePolicyId() string {
	if x != nil {
		return x.FailurePolicyId
	}
	return ""
}

type UpdateRoutePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Policy        *RoutePolicy           `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoutePolicyResponse) Reset() {
	*x = UpdateRoutePolicyResponse{}
	mi := &file_control_plane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoutePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutePolicyResponse) ProtoMessage() {}

func (x *UpdateRoutePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutePolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoutePolicyResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateRoutePolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRoutePolicyResponse) GetPolicy() *RoutePolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *UpdateRoutePolicyResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type RoutePolicy struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessPolicyId         string                 `protobuf:"bytes,2,opt,name=accessPolicyId,proto3" json:"accessPolicyId,omitempty"`
	RoutePattern           string                 `protobuf:"bytes,3,opt,name=routePattern,proto3" json:"routePattern,omitempty"`
	Semantics              string                 `protobuf:"bytes,4,opt,name=semantics,proto3" json:"semantics,omitempty"`
	RequiredCapabilityTier string                 `protobuf:"bytes,5,opt,name=requiredCapabilityTier,proto3" json:"requiredCapabilityTier,omitempty"`
	IntentClass            string                 `protobuf:"bytes,6,opt,name=intentClass,proto3" json:"intentClass,omitempty"`
	AuthRequired           bool                   `protobuf:"varint,7,opt,name=authRequired,proto3" json:"authRequired,omitempty"`
	TenantScopeRequired    bool                   `protobuf:"varint,8,opt,name=tenantScopeRequired,proto3" json:"tenantScopeRequired,omitempty"`
	TemporalRuleId         string                 `protobuf:"bytes,9,opt,name=temporalRuleId,proto3" json:"temporalRuleId,omitempty"`
	FailurePolicyId        string                 `protobuf:"bytes,10,opt,name=failurePolicyId,proto3" json:"failurePolicyId,omitempty"`
	CreatedAt              int64                  `protobuf:"varint,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt              int64                  `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RoutePolicy) Reset() {
	*x = RoutePolicy{}
	mi := &file_control_plane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicy) ProtoMessage() {}

func (x *RoutePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicy.ProtoReflect.Descriptor instead.
func (*RoutePolicy) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{14}
}

func (x *RoutePolicy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoutePolicy) GetAccessPolicyId() string {
	if x != nil {
		return x.AccessPolicyId
	}
	return ""
}

func (x *RoutePolicy) GetRoutePattern() string {
	if x != nil {
		return x.RoutePattern
	}
	return ""
}

func (x *RoutePolicy) GetSemantics() string {
	if x != nil {
		return x.Semantics
	}
	return ""
}

func (x *RoutePolicy) GetRequiredCapabilityTier() string {
	if x != nil {
		return x.RequiredCapabilityTier
	}
	return ""
}

func (x *RoutePolicy) GetIntentClass() string {
	if x != nil {
		return x.IntentClass
	}
	return ""
}

func (x *RoutePolicy) GetAuthRequired() bool {
	if x != nil {
		return x.AuthRequired
	}
	return false
}

func (x *RoutePolicy) GetTenantScopeRequired() bool {
	if x != nil {
		return x.TenantScopeRequired
	}
	return false
}

func (x *RoutePolicy) GetTemporalRuleId() string {
	if x != nil {
		return x.TemporalRuleId
	}
	return ""
}

func (x *RoutePolicy) GetFailurePolicyId() string {
	if x != nil {
		return x.FailurePolicyId
	}
	return ""
}

func (x *RoutePolicy) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *RoutePolicy) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Validate Policy Configuration
type ValidatePolicyConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePolicyConfigurationRequest) Reset() {
	*x = ValidatePolicyConfigurationRequest{}
	mi := &file_control_plane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePolicyConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePolicyConfigurationRequest) ProtoMessage() {}

func (x *ValidatePolicyConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePolicyConfigurationRequest.ProtoReflect.Descriptor instead.
func (*ValidatePolicyConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{15}
}

func (x *ValidatePolicyConfigurationRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ValidatePolicyConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
	Issues        []string               `protobuf:"bytes,2,rep,name=issues,proto3" json:"issues,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePolicyConfigurationResponse) Reset() {
	*x = ValidatePolicyConfigurationResponse{}
	mi := &file_control_plane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePolicyConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePolicyConfigurationResponse) ProtoMessage() {}

func (x *ValidatePolicyConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePolicyConfigurationResponse.ProtoReflect.Descriptor instead.
func (*ValidatePolicyConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{16}
}

func (x *ValidatePolicyConfigurationResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidatePolicyConfigurationResponse) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ValidatePolicyConfigurationResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

// Health Check
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_control_plane_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{17}
}

func (x *HealthCheckRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsHealthy     bool                   `protobuf:"varint,1,opt,name=isHealthy,proto3" json:"isHealthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_control_plane_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckResponse) GetIsHealthy() bool {
	if x != nil {
		return x.IsHealthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteCapabilityTierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCapabilityTierRequest) Reset() {
	*x = DeleteCapabilityTierRequest{}
	mi := &file_control_plane_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCapabilityTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCapabilityTierRequest) ProtoMessage() {}

func (x *DeleteCapabilityTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCapabilityTierRequest.ProtoReflect.Descriptor instead.
func (*DeleteCapabilityTierRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteCapabilityTierRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteCapabilityTierRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteCapabilityTierRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CreateRoutePolicyRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Context                *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	TenantId               string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AccessPolicyId         string                 `protobuf:"bytes,3,opt,name=access_policy_id,json=accessPolicyId,proto3" json:"access_policy_id,omitempty"`
	RoutePattern           string                 `protobuf:"bytes,4,opt,name=route_pattern,json=routePattern,proto3" json:"route_pattern,omitempty"`
	Semantics              string                 `protobuf:"bytes,5,opt,name=semantics,proto3" json:"semantics,omitempty"`
	RequiredCapabilityTier string                 `protobuf:"bytes,6,opt,name=required_capability_tier,json=requiredCapabilityTier,proto3" json:"required_capability_tier,omitempty"`
	IntentClass            string                 `protobuf:"bytes,7,opt,name=intent_class,json=intentClass,proto3" json:"intent_class,omitempty"`
	AuthRequired           bool                   `protobuf:"varint,8,opt,name=auth_required,json=authRequired,proto3" json:"auth_required,omitempty"`
	TenantScopeRequired    bool                   `protobuf:"varint,9,opt,name=tenant_scope_required,json=tenantScopeRequired,proto3" json:"tenant_scope_required,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateRoutePolicyRequest) Reset() {
	*x = CreateRoutePolicyRequest{}
	mi := &file_control_plane_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoutePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoutePolicyRequest) ProtoMessage() {}

func (x *CreateRoutePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoutePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreateRoutePolicyRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{20}
}

func (x *CreateRoutePolicyRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CreateRoutePolicyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateRoutePolicyRequest) GetAccessPolicyId() string {
	if x != nil {
		return x.AccessPolicyId
	}
	return ""
}

func (x *CreateRoutePolicyRequest) GetRoutePattern() string {
	if x != nil {
		return x.RoutePattern
	}
	return ""
}

func (x *CreateRoutePolicyRequest) GetSemantics() string {
	if x != nil {
		return x.Semantics
	}
	return ""
}

func (x *CreateRoutePolicyRequest) GetRequiredCapabilityTier() string {
	if x != nil {
		return x.RequiredCapabilityTier
	}
	return ""
}

func (x *CreateRoutePolicyRequest) GetIntentClass() string {
	if x != nil {
		return x.IntentClass
	}
	return ""
}

func (x *CreateRoutePolicyRequest) GetAuthRequired() bool {
	if x != nil {
		return x.AuthRequired
	}
	return false
}

func (x *CreateRoutePolicyRequest) GetTenantScopeRequired() bool {
	if x != nil {
		return x.TenantScopeRequired
	}
	return false
}

type CreateRoutePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Policy        *RoutePolicy           `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	Error         *ErrorResponse         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoutePolicyResponse) Reset() {
	*x = CreateRoutePolicyResponse{}
	mi := &file_control_plane_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoutePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoutePolicyResponse) ProtoMessage() {}

func (x *CreateRoutePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoutePolicyResponse.ProtoReflect.Descriptor instead.
func (*CreateRoutePolicyResponse) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{21}
}

func (x *CreateRoutePolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRoutePolicyResponse) GetPolicy() *RoutePolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *CreateRoutePolicyResponse) GetError() *ErrorResponse {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteRoutePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoutePolicyRequest) Reset() {
	*x = DeleteRoutePolicyRequest{}
	mi := &file_control_plane_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoutePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoutePolicyRequest) ProtoMessage() {}

func (x *DeleteRoutePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoutePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoutePolicyRequest) Descriptor() ([]byte, []int) {
	return file_control_plane_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteRoutePolicyRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteRoutePolicyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRoutePolicyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

var File_control_plane_proto protoreflect.FileDescriptor

const file_control_plane_proto_rawDesc = "" +
	"\n" +
	"\x13control-plane.proto\x12\fcontrolplane\x1a\fcommon.proto\"f\n" +
	"\x18GetPolicyManifestRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x9c\x01\n" +
	"\x19GetPolicyManifestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\bmanifest\x18\x02 \x01(\v2\x1c.controlplane.PolicyManifestR\bmanifest\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error\"\xfe\x03\n" +
	"\x0ePolicyManifest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x129\n" +
	"\x06routes\x18\x03 \x03(\v2!.controlplane.RoutePolicyManifestR\x06routes\x12:\n" +
	"\x05tiers\x18\x04 \x03(\v2$.controlplane.CapabilityTierManifestR\x05tiers\x12M\n" +
	"\x0ffailurePolicies\x18\x05 \x03(\v2#.controlplane.FailurePolicyManifestR\x0ffailurePolicies\x12H\n" +
	"\rtemporalRules\x18\x06 \x03(\v2\".controlplane.TemporalRuleManifestR\rtemporalRules\x12Q\n" +
	"\x10environmentRules\x18\a \x03(\v2%.controlplane.EnvironmentRuleManifestR\x10environmentRules\x12Q\n" +
	"\x10upgradePipelines\x18\b \x03(\v2%.controlplane.UpgradePipelineManifestR\x10upgradePipelines\"\xd9\x02\n" +
	"\x13RoutePolicyManifest\x12\"\n" +
	"\froutePattern\x18\x01 \x01(\tR\froutePattern\x12\x1c\n" +
	"\tsemantics\x18\x02 \x01(\tR\tsemantics\x126\n" +
	"\x16requiredCapabilityTier\x18\x03 \x01(\tR\x16requiredCapabilityTier\x12 \n" +
	"\vintentClass\x18\x04 \x01(\tR\vintentClass\x12\"\n" +
	"\fauthRequired\x18\x05 \x01(\bR\fauthRequired\x120\n" +
	"\x13tenantScopeRequired\x18\x06 \x01(\bR\x13tenantScopeRequired\x12&\n" +
	"\x0etemporalRuleId\x18\a \x01(\tR\x0etemporalRuleId\x12(\n" +
	"\x0ffailurePolicyId\x18\b \x01(\tR\x0ffailurePolicyId\"\xd4\x03\n" +
	"\x16CapabilityTierManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\btierType\x18\x02 \x01(\tR\btierType\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\x12&\n" +
	"\x0eupgradePathIds\x18\x04 \x03(\tR\x0eupgradePathIds\x12l\n" +
	"\x12expirationDefaults\x18\x05 \x03(\v2<.controlplane.CapabilityTierManifest.ExpirationDefaultsEntryR\x12expirationDefaults\x12W\n" +
	"\vpermissions\x18\x06 \x03(\v25.controlplane.CapabilityTierManifest.PermissionsEntryR\vpermissions\x1aE\n" +
	"\x17ExpirationDefaultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x01\n" +
	"\x15FailurePolicyManifest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fbehaviorType\x18\x02 \x01(\tR\fbehaviorType\x12\\\n" +
	"\rconfiguration\x18\x03 \x03(\v26.controlplane.FailurePolicyManifest.ConfigurationEntryR\rconfiguration\x1a@\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x14TemporalRuleManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bruleType\x18\x03 \x01(\tR\bruleType\x12[\n" +
	"\rconfiguration\x18\x04 \x03(\v25.controlplane.TemporalRuleManifest.ConfigurationEntryR\rconfiguration\x1a@\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\x17EnvironmentRuleManifest\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12\"\n" +
	"\froutePattern\x18\x02 \x01(\tR\froutePattern\x12R\n" +
	"\toverrides\x18\x03 \x03(\v24.controlplane.EnvironmentRuleManifest.OverridesEntryR\toverrides\x1a<\n" +
	"\x0eOverridesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x03\n" +
	"\x17UpgradePipelineManifest\x12\x1a\n" +
	"\bfromTier\x18\x01 \x01(\tR\bfromTier\x12\x16\n" +
	"\x06toTier\x18\x02 \x01(\tR\x06toTier\x12^\n" +
	"\rpreservedData\x18\x03 \x03(\v28.controlplane.UpgradePipelineManifest.PreservedDataEntryR\rpreservedData\x12y\n" +
	"\x16ownershipTransferRules\x18\x04 \x03(\v2A.controlplane.UpgradePipelineManifest.OwnershipTransferRulesEntryR\x16ownershipTransferRules\x126\n" +
	"\x16sessionUpgradeBehavior\x18\x05 \x01(\tR\x16sessionUpgradeBehavior\x1a@\n" +
	"\x12PreservedDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aI\n" +
	"\x1bOwnershipTransferRulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xef\x04\n" +
	"\x1bCreateCapabilityTierRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\btierType\x18\x04 \x01(\tR\btierType\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x05R\x05order\x12&\n" +
	"\x0eupgradePathIds\x18\x06 \x03(\tR\x0eupgradePathIds\x12q\n" +
	"\x12expirationDefaults\x18\a \x03(\v2A.controlplane.CreateCapabilityTierRequest.ExpirationDefaultsEntryR\x12expirationDefaults\x12\\\n" +
	"\vpermissions\x18\b \x03(\v2:.controlplane.CreateCapabilityTierRequest.PermissionsEntryR\vpermissions\x12\x1a\n" +
	"\bisActive\x18\t \x01(\bR\bisActive\x12\x1a\n" +
	"\btenantId\x18\n" +
	" \x01(\tR\btenantId\x1aE\n" +
	"\x17ExpirationDefaultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x97\x01\n" +
	"\x1cCreateCapabilityTierResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\x04tier\x18\x02 \x01(\v2\x1c.controlplane.CapabilityTierR\x04tier\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error\"\xe2\x04\n" +
	"\x0eCapabilityTier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\btenantId\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\btierType\x18\x05 \x01(\tR\btierType\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x05R\x05order\x12&\n" +
	"\x0eupgradePathIds\x18\a \x03(\tR\x0eupgradePathIds\x12d\n" +
	"\x12expirationDefaults\x18\b \x03(\v24.controlplane.CapabilityTier.ExpirationDefaultsEntryR\x12expirationDefaults\x12O\n" +
	"\vpermissions\x18\t \x03(\v2-.controlplane.CapabilityTier.PermissionsEntryR\vpermissions\x12\x1a\n" +
	"\bisActive\x18\n" +
	" \x01(\bR\bisActive\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\x03R\tupdatedAt\x1aE\n" +
	"\x17ExpirationDefaultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x03\n" +
	"\x18UpdateRoutePolicyRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x1a\n" +
	"\bpolicyId\x18\x02 \x01(\tR\bpolicyId\x12\"\n" +
	"\froutePattern\x18\x03 \x01(\tR\froutePattern\x12\x1c\n" +
	"\tsemantics\x18\x04 \x01(\tR\tsemantics\x126\n" +
	"\x16requiredCapabilityTier\x18\x05 \x01(\tR\x16requiredCapabilityTier\x12 \n" +
	"\vintentClass\x18\x06 \x01(\tR\vintentClass\x12\"\n" +
	"\fauthRequired\x18\a \x01(\bR\fauthRequired\x120\n" +
	"\x13tenantScopeRequired\x18\b \x01(\bR\x13tenantScopeRequired\x12&\n" +
	"\x0etemporalRuleId\x18\t \x01(\tR\x0etemporalRuleId\x12(\n" +
	"\x0ffailurePolicyId\x18\n" +
	" \x01(\tR\x0ffailurePolicyId\"\x95\x01\n" +
	"\x19UpdateRoutePolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\x06policy\x18\x02 \x01(\v2\x19.controlplane.RoutePolicyR\x06policy\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error\"\xc5\x03\n" +
	"\vRoutePolicy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0eaccessPolicyId\x18\x02 \x01(\tR\x0eaccessPolicyId\x12\"\n" +
	"\froutePattern\x18\x03 \x01(\tR\froutePattern\x12\x1c\n" +
	"\tsemantics\x18\x04 \x01(\tR\tsemantics\x126\n" +
	"\x16requiredCapabilityTier\x18\x05 \x01(\tR\x16requiredCapabilityTier\x12 \n" +
	"\vintentClass\x18\x06 \x01(\tR\vintentClass\x12\"\n" +
	"\fauthRequired\x18\a \x01(\bR\fauthRequired\x120\n" +
	"\x13tenantScopeRequired\x18\b \x01(\bR\x13tenantScopeRequired\x12&\n" +
	"\x0etemporalRuleId\x18\t \x01(\tR\x0etemporalRuleId\x12(\n" +
	"\x0ffailurePolicyId\x18\n" +
	" \x01(\tR\x0ffailurePolicyId\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\x03R\tupdatedAt\"V\n" +
	"\"ValidatePolicyConfigurationRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\"\x84\x01\n" +
	"#ValidatePolicyConfigurationResponse\x12\x18\n" +
	"\aisValid\x18\x01 \x01(\bR\aisValid\x12\x16\n" +
	"\x06issues\x18\x02 \x03(\tR\x06issues\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error\"F\n" +
	"\x12HealthCheckRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\"z\n" +
	"\x13HealthCheckResponse\x12\x1c\n" +
	"\tisHealthy\x18\x01 \x01(\bR\tisHealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error\"|\n" +
	"\x1bDeleteCapabilityTierRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\x8c\x03\n" +
	"\x18CreateRoutePolicyRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12(\n" +
	"\x10access_policy_id\x18\x03 \x01(\tR\x0eaccessPolicyId\x12#\n" +
	"\rroute_pattern\x18\x04 \x01(\tR\froutePattern\x12\x1c\n" +
	"\tsemantics\x18\x05 \x01(\tR\tsemantics\x128\n" +
	"\x18required_capability_tier\x18\x06 \x01(\tR\x16requiredCapabilityTier\x12!\n" +
	"\fintent_class\x18\a \x01(\tR\vintentClass\x12#\n" +
	"\rauth_required\x18\b \x01(\bR\fauthRequired\x122\n" +
	"\x15tenant_scope_required\x18\t \x01(\bR\x13tenantScopeRequired\"\x95\x01\n" +
	"\x19CreateRoutePolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\x06policy\x18\x02 \x01(\v2\x19.controlplane.RoutePolicyR\x06policy\x12+\n" +
	"\x05error\x18\x03 \x01(\v2\x15.common.ErrorResponseR\x05error\"y\n" +
	"\x18DeleteRoutePolicyRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.common.RequestContextR\acontext\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId2\xa9\a\n" +
	"\x13ControlPlaneService\x12d\n" +
	"\x11GetPolicyManifest\x12&.controlplane.GetPolicyManifestRequest\x1a'.controlplane.GetPolicyManifestResponse\x12m\n" +
	"\x14CreateCapabilityTier\x12).controlplane.CreateCapabilityTierRequest\x1a*.controlplane.CreateCapabilityTierResponse\x12d\n" +
	"\x11UpdateRoutePolicy\x12&.controlplane.UpdateRoutePolicyRequest\x1a'.controlplane.UpdateRoutePolicyResponse\x12\x82\x01\n" +
	"\x1bValidatePolicyConfiguration\x120.controlplane.ValidatePolicyConfigurationRequest\x1a1.controlplane.ValidatePolicyConfigurationResponse\x12R\n" +
	"\vHealthCheck\x12 .controlplane.HealthCheckRequest\x1a!.controlplane.HealthCheckResponse\x12h\n" +
	"\x13StreamPolicyUpdates\x12&.controlplane.GetPolicyManifestRequest\x1a'.controlplane.GetPolicyManifestResponse0\x01\x12Y\n" +
	"\x14DeleteCapabilityTier\x12).controlplane.DeleteCapabilityTierRequest\x1a\x16.common.DeleteResponse\x12d\n" +
	"\x11CreateRoutePolicy\x12&.controlplane.CreateRoutePolicyRequest\x1a'.controlplane.CreateRoutePolicyResponse\x12S\n" +
	"\x11DeleteRoutePolicy\x12&.controlplane.DeleteRoutePolicyRequest\x1a\x16.common.DeleteResponseB\x96\x01\n" +
	"\x10com.controlplaneB\x11ControlPlaneProtoP\x01Z\x1fgithub.com/yourorg/sdk/go/proto\xa2\x02\x03CXX\xaa\x02\fControlplane\xca\x02\fControlplane\xe2\x02\x18Controlplane\\GPBMetadata\xea\x02\fControlplaneb\x06proto3"

var (
	file_control_plane_proto_rawDescOnce sync.Once
	file_control_plane_proto_rawDescData []byte
)

func file_control_plane_proto_rawDescGZIP() []byte {
	file_control_plane_proto_rawDescOnce.Do(func() {
		file_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)))
	})
	return file_control_plane_proto_rawDescData
}

var file_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_control_plane_proto_goTypes = []any{
	(*GetPolicyManifestRequest)(nil),            // 0: controlplane.GetPolicyManifestRequest
	(*GetPolicyManifestResponse)(nil),           // 1: controlplane.GetPolicyManifestResponse
	(*PolicyManifest)(nil),                      // 2: controlplane.PolicyManifest
	(*RoutePolicyManifest)(nil),                 // 3: controlplane.RoutePolicyManifest
	(*CapabilityTierManifest)(nil),              // 4: controlplane.CapabilityTierManifest
	(*FailurePolicyManifest)(nil),               // 5: controlplane.FailurePolicyManifest
	(*TemporalRuleManifest)(nil),                // 6: controlplane.TemporalRuleManifest
	(*EnvironmentRuleManifest)(nil),             // 7: controlplane.EnvironmentRuleManifest
	(*UpgradePipelineManifest)(nil),             // 8: controlplane.UpgradePipelineManifest
	(*CreateCapabilityTierRequest)(nil),         // 9: controlplane.CreateCapabilityTierRequest
	(*CreateCapabilityTierResponse)(nil),        // 10: controlplane.CreateCapabilityTierResponse
	(*CapabilityTier)(nil),                      // 11: controlplane.CapabilityTier
	(*UpdateRoutePolicyRequest)(nil),            // 12: controlplane.UpdateRoutePolicyRequest
	(*UpdateRoutePolicyResponse)(nil),           // 13: controlplane.UpdateRoutePolicyResponse
	(*RoutePolicy)(nil),                         // 14: controlplane.RoutePolicy
	(*ValidatePolicyConfigurationRequest)(nil),  // 15: controlplane.ValidatePolicyConfigurationRequest
	(*ValidatePolicyConfigurationResponse)(nil), // 16: controlplane.ValidatePolicyConfigurationResponse
	(*HealthCheckRequest)(nil),                  // 17: controlplane.HealthCheckRequest
	(*HealthCheckResponse)(nil),                 // 18: controlplane.HealthCheckResponse
	(*DeleteCapabilityTierRequest)(nil),         // 19: controlplane.DeleteCapabilityTierRequest
	(*CreateRoutePolicyRequest)(nil),            // 20: controlplane.CreateRoutePolicyRequest
	(*CreateRoutePolicyResponse)(nil),           // 21: controlplane.CreateRoutePolicyResponse
	(*DeleteRoutePolicyRequest)(nil),            // 22: controlplane.DeleteRoutePolicyRequest
	nil,                                         // 23: controlplane.CapabilityTierManifest.ExpirationDefaultsEntry
	nil,                                         // 24: controlplane.CapabilityTierManifest.PermissionsEntry
	nil,                                         // 25: controlplane.FailurePolicyManifest.ConfigurationEntry
	nil,                                         // 26: controlplane.TemporalRuleManifest.ConfigurationEntry
	nil,                                         // 27: controlplane.EnvironmentRuleManifest.OverridesEntry
	nil,                                         // 28: controlplane.UpgradePipelineManifest.PreservedDataEntry
	nil,                                         // 29: controlplane.UpgradePipelineManifest.OwnershipTransferRulesEntry
	nil,                                         // 30: controlplane.CreateCapabilityTierRequest.ExpirationDefaultsEntry
	nil,                                         // 31: controlplane.CreateCapabilityTierRequest.PermissionsEntry
	nil,                                         // 32: controlplane.CapabilityTier.ExpirationDefaultsEntry
	nil,                                         // 33: controlplane.CapabilityTier.PermissionsEntry
	(*RequestContext)(nil),                      // 34: common.RequestContext
	(*ErrorResponse)(nil),                       // 35: common.ErrorResponse
	(*DeleteResponse)(nil),                      // 36: common.DeleteResponse
}
var file_control_plane_proto_depIdxs = []int32{
	34, // 0: controlplane.GetPolicyManifestRequest.context:type_name -> common.RequestContext
	2,  // 1: controlplane.GetPolicyManifestResponse.manifest:type_name -> controlplane.PolicyManifest
	35, // 2: controlplane.GetPolicyManifestResponse.error:type_name -> common.ErrorResponse
	3,  // 3: controlplane.PolicyManifest.routes:type_name -> controlplane.RoutePolicyManifest
	4,  // 4: controlplane.PolicyManifest.tiers:type_name -> controlplane.CapabilityTierManifest
	5,  // 5: controlplane.PolicyManifest.failurePolicies:type_name -> controlplane.FailurePolicyManifest
	6,  // 6: controlplane.PolicyManifest.temporalRules:type_name -> controlplane.TemporalRuleManifest
	7,  // 7: controlplane.PolicyManifest.environmentRules:type_name -> controlplane.EnvironmentRuleManifest
	8,  // 8: controlplane.PolicyManifest.upgradePipelines:type_name -> controlplane.UpgradePipelineManifest
	23, // 9: controlplane.CapabilityTierManifest.expirationDefaults:type_name -> controlplane.CapabilityTierManifest.ExpirationDefaultsEntry
	24, // 10: controlplane.CapabilityTierManifest.permissions:type_name -> controlplane.CapabilityTierManifest.PermissionsEntry
	25, // 11: controlplane.FailurePolicyManifest.configuration:type_name -> controlplane.FailurePolicyManifest.ConfigurationEntry
	26, // 12: controlplane.TemporalRuleManifest.configuration:type_name -> controlplane.TemporalRuleManifest.ConfigurationEntry
	27, // 13: controlplane.EnvironmentRuleManifest.overrides:type_name -> controlplane.EnvironmentRuleManifest.OverridesEntry
	28, // 14: controlplane.UpgradePipelineManifest.preservedData:type_name -> controlplane.UpgradePipelineManifest.PreservedDataEntry
	29, // 15: controlplane.UpgradePipelineManifest.ownershipTransferRules:type_name -> controlplane.UpgradePipelineManifest.OwnershipTransferRulesEntry
	34, // 16: controlplane.CreateCapabilityTierRequest.context:type_name -> common.RequestContext
	30, // 17: controlplane.CreateCapabilityTierRequest.expirationDefaults:type_name -> controlplane.CreateCapabilityTierRequest.ExpirationDefaultsEntry
	31, // 18: controlplane.CreateCapabilityTierRequest.permissions:type_name -> controlplane.CreateCapabilityTierRequest.PermissionsEntry
	11, // 19: controlplane.CreateCapabilityTierResponse.tier:type_name -> controlplane.CapabilityTier
	35, // 20: controlplane.CreateCapabilityTierResponse.error:type_name -> common.ErrorResponse
	32, // 21: controlplane.CapabilityTier.expirationDefaults:type_name -> controlplane.CapabilityTier.ExpirationDefaultsEntry
	33, // 22: controlplane.CapabilityTier.permissions:type_name -> controlplane.CapabilityTier.PermissionsEntry
	34, // 23: controlplane.UpdateRoutePolicyRequest.context:type_name -> common.RequestContext
	14, // 24: controlplane.UpdateRoutePolicyResponse.policy:type_name -> controlplane.RoutePolicy
	35, // 25: controlplane.UpdateRoutePolicyResponse.error:type_name -> common.ErrorResponse
	34, // 26: controlplane.ValidatePolicyConfigurationRequest.context:type_name -> common.RequestContext
	35, // 27: controlplane.ValidatePolicyConfigurationResponse.error:type_name -> common.ErrorResponse
	34, // 28: controlplane.HealthCheckRequest.context:type_name -> common.RequestContext
	35, // 29: controlplane.HealthCheckResponse.error:type_name -> common.ErrorResponse
	34, // 30: controlplane.DeleteCapabilityTierRequest.context:type_name -> common.RequestContext
	34, // 31: controlplane.CreateRoutePolicyRequest.context:type_name -> common.RequestContext
	14, // 32: controlplane.CreateRoutePolicyResponse.policy:type_name -> controlplane.RoutePolicy
	35, // 33: controlplane.CreateRoutePolicyResponse.error:type_name -> common.ErrorResponse
	34, // 34: controlplane.DeleteRoutePolicyRequest.context:type_name -> common.RequestContext
	0,  // 35: controlplane.ControlPlaneService.GetPolicyManifest:input_type -> controlplane.GetPolicyManifestRequest
	9,  // 36: controlplane.ControlPlaneService.CreateCapabilityTier:input_type -> controlplane.CreateCapabilityTierRequest
	12, // 37: controlplane.ControlPlaneService.UpdateRoutePolicy:input_type -> controlplane.UpdateRoutePolicyRequest
	15, // 38: controlplane.ControlPlaneService.ValidatePolicyConfiguration:input_type -> controlplane.ValidatePolicyConfigurationRequest
	17, // 39: controlplane.ControlPlaneService.HealthCheck:input_type -> controlplane.HealthCheckRequest
	0,  // 40: controlplane.ControlPlaneService.StreamPolicyUpdates:input_type -> controlplane.GetPolicyManifestRequest
	19, // 41: controlplane.ControlPlaneService.DeleteCapabilityTier:input_type -> controlplane.DeleteCapabilityTierRequest
	20, // 42: controlplane.ControlPlaneService.CreateRoutePolicy:input_type -> controlplane.CreateRoutePolicyRequest
	22, // 43: controlplane.ControlPlaneService.DeleteRoutePolicy:input_type -> controlplane.DeleteRoutePolicyRequest
	1,  // 44: controlplane.ControlPlaneService.GetPolicyManifest:output_type -> controlplane.GetPolicyManifestResponse
	10, // 45: controlplane.ControlPlaneService.CreateCapabilityTier:output_type -> controlplane.CreateCapabilityTierResponse
	13, // 46: controlplane.ControlPlaneService.UpdateRoutePolicy:output_type -> controlplane.UpdateRoutePolicyResponse
	16, // 47: controlplane.ControlPlaneService.ValidatePolicyConfiguration:output_type -> controlplane.ValidatePolicyConfigurationResponse
	18, // 48: controlplane.ControlPlaneService.HealthCheck:output_type -> controlplane.HealthCheckResponse
	1,  // 49: controlplane.ControlPlaneService.StreamPolicyUpdates:output_type -> controlplane.GetPolicyManifestResponse
	36, // 50: controlplane.ControlPlaneService.DeleteCapabilityTier:output_type -> common.DeleteResponse
	21, // 51: controlplane.ControlPlaneService.CreateRoutePolicy:output_type -> controlplane.CreateRoutePolicyResponse
	36, // 52: controlplane.ControlPlaneService.DeleteRoutePolicy:output_type -> common.DeleteResponse
	44, // [44:53] is the sub-list for method output_type
	35, // [35:44] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_control_plane_proto_init() }
func file_control_plane_proto_init() {
	if File_control_plane_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_plane_proto_rawDesc), len(file_control_plane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_plane_proto_goTypes,
		DependencyIndexes: file_control_plane_proto_depIdxs,
		MessageInfos:      file_control_plane_proto_msgTypes,
	}.Build()
	File_control_plane_proto = out.File
	file_control_plane_proto_goTypes = nil
	file_control_plane_proto_depIdxs = nil
}
