// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: security.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecurityService_ValidateAccess_FullMethodName  = "/security.SecurityService/ValidateAccess"
	SecurityService_CheckIP_FullMethodName         = "/security.SecurityService/CheckIP"
	SecurityService_DetectBot_FullMethodName       = "/security.SecurityService/DetectBot"
	SecurityService_ValidateDevice_FullMethodName  = "/security.SecurityService/ValidateDevice"
	SecurityService_ReportIncident_FullMethodName  = "/security.SecurityService/ReportIncident"
	SecurityService_GetIPReputation_FullMethodName = "/security.SecurityService/GetIPReputation"
)

// SecurityServiceClient is the client API for SecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecurityServiceClient interface {
	// NEW: Unified Access Validation
	// This combines IP, Bot, Device, and Behavioral analysis in one fast call
	ValidateAccess(ctx context.Context, in *ValidateAccessRequest, opts ...grpc.CallOption) (*ValidateAccessResponse, error)
	// IP reputation check - called by Gateway
	CheckIP(ctx context.Context, in *CheckIPRequest, opts ...grpc.CallOption) (*CheckIPResponse, error)
	// Bot detection
	DetectBot(ctx context.Context, in *DetectBotRequest, opts ...grpc.CallOption) (*DetectBotResponse, error)
	// Device fingerprint validation
	ValidateDevice(ctx context.Context, in *ValidateDeviceRequest, opts ...grpc.CallOption) (*ValidateDeviceResponse, error)
	// Report security incident
	ReportIncident(ctx context.Context, in *ReportIncidentRequest, opts ...grpc.CallOption) (*ReportIncidentResponse, error)
	// Get IP reputation details
	GetIPReputation(ctx context.Context, in *GetIPReputationRequest, opts ...grpc.CallOption) (*GetIPReputationResponse, error)
}

type securityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityServiceClient(cc grpc.ClientConnInterface) SecurityServiceClient {
	return &securityServiceClient{cc}
}

func (c *securityServiceClient) ValidateAccess(ctx context.Context, in *ValidateAccessRequest, opts ...grpc.CallOption) (*ValidateAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAccessResponse)
	err := c.cc.Invoke(ctx, SecurityService_ValidateAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) CheckIP(ctx context.Context, in *CheckIPRequest, opts ...grpc.CallOption) (*CheckIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckIPResponse)
	err := c.cc.Invoke(ctx, SecurityService_CheckIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) DetectBot(ctx context.Context, in *DetectBotRequest, opts ...grpc.CallOption) (*DetectBotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectBotResponse)
	err := c.cc.Invoke(ctx, SecurityService_DetectBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) ValidateDevice(ctx context.Context, in *ValidateDeviceRequest, opts ...grpc.CallOption) (*ValidateDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateDeviceResponse)
	err := c.cc.Invoke(ctx, SecurityService_ValidateDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) ReportIncident(ctx context.Context, in *ReportIncidentRequest, opts ...grpc.CallOption) (*ReportIncidentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportIncidentResponse)
	err := c.cc.Invoke(ctx, SecurityService_ReportIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) GetIPReputation(ctx context.Context, in *GetIPReputationRequest, opts ...grpc.CallOption) (*GetIPReputationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIPReputationResponse)
	err := c.cc.Invoke(ctx, SecurityService_GetIPReputation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityServiceServer is the server API for SecurityService service.
// All implementations must embed UnimplementedSecurityServiceServer
// for forward compatibility.
type SecurityServiceServer interface {
	// NEW: Unified Access Validation
	// This combines IP, Bot, Device, and Behavioral analysis in one fast call
	ValidateAccess(context.Context, *ValidateAccessRequest) (*ValidateAccessResponse, error)
	// IP reputation check - called by Gateway
	CheckIP(context.Context, *CheckIPRequest) (*CheckIPResponse, error)
	// Bot detection
	DetectBot(context.Context, *DetectBotRequest) (*DetectBotResponse, error)
	// Device fingerprint validation
	ValidateDevice(context.Context, *ValidateDeviceRequest) (*ValidateDeviceResponse, error)
	// Report security incident
	ReportIncident(context.Context, *ReportIncidentRequest) (*ReportIncidentResponse, error)
	// Get IP reputation details
	GetIPReputation(context.Context, *GetIPReputationRequest) (*GetIPReputationResponse, error)
	mustEmbedUnimplementedSecurityServiceServer()
}

// UnimplementedSecurityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityServiceServer struct{}

func (UnimplementedSecurityServiceServer) ValidateAccess(context.Context, *ValidateAccessRequest) (*ValidateAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAccess not implemented")
}
func (UnimplementedSecurityServiceServer) CheckIP(context.Context, *CheckIPRequest) (*CheckIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIP not implemented")
}
func (UnimplementedSecurityServiceServer) DetectBot(context.Context, *DetectBotRequest) (*DetectBotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectBot not implemented")
}
func (UnimplementedSecurityServiceServer) ValidateDevice(context.Context, *ValidateDeviceRequest) (*ValidateDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateDevice not implemented")
}
func (UnimplementedSecurityServiceServer) ReportIncident(context.Context, *ReportIncidentRequest) (*ReportIncidentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportIncident not implemented")
}
func (UnimplementedSecurityServiceServer) GetIPReputation(context.Context, *GetIPReputationRequest) (*GetIPReputationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIPReputation not implemented")
}
func (UnimplementedSecurityServiceServer) mustEmbedUnimplementedSecurityServiceServer() {}
func (UnimplementedSecurityServiceServer) testEmbeddedByValue()                         {}

// UnsafeSecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityServiceServer will
// result in compilation errors.
type UnsafeSecurityServiceServer interface {
	mustEmbedUnimplementedSecurityServiceServer()
}

func RegisterSecurityServiceServer(s grpc.ServiceRegistrar, srv SecurityServiceServer) {
	// If the following call panics, it indicates UnimplementedSecurityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityService_ServiceDesc, srv)
}

func _SecurityService_ValidateAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).ValidateAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_ValidateAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).ValidateAccess(ctx, req.(*ValidateAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_CheckIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).CheckIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_CheckIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).CheckIP(ctx, req.(*CheckIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_DetectBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectBotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).DetectBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_DetectBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).DetectBot(ctx, req.(*DetectBotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_ValidateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).ValidateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_ValidateDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).ValidateDevice(ctx, req.(*ValidateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_ReportIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).ReportIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_ReportIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).ReportIncident(ctx, req.(*ReportIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_GetIPReputation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPReputationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).GetIPReputation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_GetIPReputation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).GetIPReputation(ctx, req.(*GetIPReputationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityService_ServiceDesc is the grpc.ServiceDesc for SecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "security.SecurityService",
	HandlerType: (*SecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateAccess",
			Handler:    _SecurityService_ValidateAccess_Handler,
		},
		{
			MethodName: "CheckIP",
			Handler:    _SecurityService_CheckIP_Handler,
		},
		{
			MethodName: "DetectBot",
			Handler:    _SecurityService_DetectBot_Handler,
		},
		{
			MethodName: "ValidateDevice",
			Handler:    _SecurityService_ValidateDevice_Handler,
		},
		{
			MethodName: "ReportIncident",
			Handler:    _SecurityService_ReportIncident_Handler,
		},
		{
			MethodName: "GetIPReputation",
			Handler:    _SecurityService_GetIPReputation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "security.proto",
}
