// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: tenant.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantService_ValidateApiKey_FullMethodName               = "/tenant.TenantService/ValidateApiKey"
	TenantService_GetTenantPolicy_FullMethodName              = "/tenant.TenantService/GetTenantPolicy"
	TenantService_GetTenant_FullMethodName                    = "/tenant.TenantService/GetTenant"
	TenantService_GetTenantHierarchy_FullMethodName           = "/tenant.TenantService/GetTenantHierarchy"
	TenantService_CheckMembership_FullMethodName              = "/tenant.TenantService/CheckMembership"
	TenantService_GetUserTenants_FullMethodName               = "/tenant.TenantService/GetUserTenants"
	TenantService_CreateTenant_FullMethodName                 = "/tenant.TenantService/CreateTenant"
	TenantService_DeleteTenant_FullMethodName                 = "/tenant.TenantService/DeleteTenant"
	TenantService_CheckSlugAvailable_FullMethodName           = "/tenant.TenantService/CheckSlugAvailable"
	TenantService_CompleteOnboarding_FullMethodName           = "/tenant.TenantService/CompleteOnboarding"
	TenantService_AddMember_FullMethodName                    = "/tenant.TenantService/AddMember"
	TenantService_RemoveMember_FullMethodName                 = "/tenant.TenantService/RemoveMember"
	TenantService_GetTenantMemberUserIds_FullMethodName       = "/tenant.TenantService/GetTenantMemberUserIds"
	TenantService_UpdateTenantWebhook_FullMethodName          = "/tenant.TenantService/UpdateTenantWebhook"
	TenantService_RotateApiKey_FullMethodName                 = "/tenant.TenantService/RotateApiKey"
	TenantService_CreateTenantRateLimitProfile_FullMethodName = "/tenant.TenantService/CreateTenantRateLimitProfile"
	TenantService_GetTenantRateLimitProfiles_FullMethodName   = "/tenant.TenantService/GetTenantRateLimitProfiles"
	TenantService_UpdateTenantRateLimitProfile_FullMethodName = "/tenant.TenantService/UpdateTenantRateLimitProfile"
	TenantService_DeleteTenantRateLimitProfile_FullMethodName = "/tenant.TenantService/DeleteTenantRateLimitProfile"
)

// TenantServiceClient is the client API for TenantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantServiceClient interface {
	ValidateApiKey(ctx context.Context, in *ValidateApiKeyRequest, opts ...grpc.CallOption) (*ValidateApiKeyResponse, error)
	GetTenantPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*TenantPolicyResponse, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*TenantResponse, error)
	GetTenantHierarchy(ctx context.Context, in *GetTenantHierarchyRequest, opts ...grpc.CallOption) (*GetTenantHierarchyResponse, error)
	CheckMembership(ctx context.Context, in *CheckMembershipRequest, opts ...grpc.CallOption) (*CheckMembershipResponse, error)
	GetUserTenants(ctx context.Context, in *GetUserTenantsRequest, opts ...grpc.CallOption) (*GetUserTenantsResponse, error)
	// --- Tenant CRUD ---
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error)
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// --- Slug ---
	CheckSlugAvailable(ctx context.Context, in *CheckSlugAvailableRequest, opts ...grpc.CallOption) (*CheckSlugAvailableResponse, error)
	// --- Onboarding ---
	CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// --- Membership ---
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	GetTenantMemberUserIds(ctx context.Context, in *GetTenantMemberUserIdsRequest, opts ...grpc.CallOption) (*GetTenantMemberUserIdsResponse, error)
	// --- Webhook ---
	UpdateTenantWebhook(ctx context.Context, in *UpdateTenantWebhookRequest, opts ...grpc.CallOption) (*UpdateTenantWebhookResponse, error)
	// --- API Key ---
	RotateApiKey(ctx context.Context, in *RotateApiKeyRequest, opts ...grpc.CallOption) (*RotateApiKeyResponse, error)
	// --- Rate Limit Profiles ---
	CreateTenantRateLimitProfile(ctx context.Context, in *CreateTenantRateLimitProfileRequest, opts ...grpc.CallOption) (*RateLimitProfileResponse, error)
	GetTenantRateLimitProfiles(ctx context.Context, in *GetTenantRateLimitProfilesRequest, opts ...grpc.CallOption) (*GetTenantRateLimitProfilesResponse, error)
	UpdateTenantRateLimitProfile(ctx context.Context, in *UpdateTenantRateLimitProfileRequest, opts ...grpc.CallOption) (*RateLimitProfileResponse, error)
	DeleteTenantRateLimitProfile(ctx context.Context, in *DeleteTenantRateLimitProfileRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type tenantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantServiceClient(cc grpc.ClientConnInterface) TenantServiceClient {
	return &tenantServiceClient{cc}
}

func (c *tenantServiceClient) ValidateApiKey(ctx context.Context, in *ValidateApiKeyRequest, opts ...grpc.CallOption) (*ValidateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateApiKeyResponse)
	err := c.cc.Invoke(ctx, TenantService_ValidateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*TenantPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantPolicyResponse)
	err := c.cc.Invoke(ctx, TenantService_GetTenantPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*TenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantResponse)
	err := c.cc.Invoke(ctx, TenantService_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantHierarchy(ctx context.Context, in *GetTenantHierarchyRequest, opts ...grpc.CallOption) (*GetTenantHierarchyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantHierarchyResponse)
	err := c.cc.Invoke(ctx, TenantService_GetTenantHierarchy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) CheckMembership(ctx context.Context, in *CheckMembershipRequest, opts ...grpc.CallOption) (*CheckMembershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckMembershipResponse)
	err := c.cc.Invoke(ctx, TenantService_CheckMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetUserTenants(ctx context.Context, in *GetUserTenantsRequest, opts ...grpc.CallOption) (*GetUserTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTenantsResponse)
	err := c.cc.Invoke(ctx, TenantService_GetUserTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*CreateTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTenantResponse)
	err := c.cc.Invoke(ctx, TenantService_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, TenantService_DeleteTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) CheckSlugAvailable(ctx context.Context, in *CheckSlugAvailableRequest, opts ...grpc.CallOption) (*CheckSlugAvailableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSlugAvailableResponse)
	err := c.cc.Invoke(ctx, TenantService_CheckSlugAvailable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) CompleteOnboarding(ctx context.Context, in *CompleteOnboardingRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, TenantService_CompleteOnboarding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, TenantService_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, TenantService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantMemberUserIds(ctx context.Context, in *GetTenantMemberUserIdsRequest, opts ...grpc.CallOption) (*GetTenantMemberUserIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantMemberUserIdsResponse)
	err := c.cc.Invoke(ctx, TenantService_GetTenantMemberUserIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) UpdateTenantWebhook(ctx context.Context, in *UpdateTenantWebhookRequest, opts ...grpc.CallOption) (*UpdateTenantWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTenantWebhookResponse)
	err := c.cc.Invoke(ctx, TenantService_UpdateTenantWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) RotateApiKey(ctx context.Context, in *RotateApiKeyRequest, opts ...grpc.CallOption) (*RotateApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateApiKeyResponse)
	err := c.cc.Invoke(ctx, TenantService_RotateApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) CreateTenantRateLimitProfile(ctx context.Context, in *CreateTenantRateLimitProfileRequest, opts ...grpc.CallOption) (*RateLimitProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateLimitProfileResponse)
	err := c.cc.Invoke(ctx, TenantService_CreateTenantRateLimitProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) GetTenantRateLimitProfiles(ctx context.Context, in *GetTenantRateLimitProfilesRequest, opts ...grpc.CallOption) (*GetTenantRateLimitProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantRateLimitProfilesResponse)
	err := c.cc.Invoke(ctx, TenantService_GetTenantRateLimitProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) UpdateTenantRateLimitProfile(ctx context.Context, in *UpdateTenantRateLimitProfileRequest, opts ...grpc.CallOption) (*RateLimitProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateLimitProfileResponse)
	err := c.cc.Invoke(ctx, TenantService_UpdateTenantRateLimitProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantServiceClient) DeleteTenantRateLimitProfile(ctx context.Context, in *DeleteTenantRateLimitProfileRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, TenantService_DeleteTenantRateLimitProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantServiceServer is the server API for TenantService service.
// All implementations must embed UnimplementedTenantServiceServer
// for forward compatibility.
type TenantServiceServer interface {
	ValidateApiKey(context.Context, *ValidateApiKeyRequest) (*ValidateApiKeyResponse, error)
	GetTenantPolicy(context.Context, *GetPolicyRequest) (*TenantPolicyResponse, error)
	GetTenant(context.Context, *GetTenantRequest) (*TenantResponse, error)
	GetTenantHierarchy(context.Context, *GetTenantHierarchyRequest) (*GetTenantHierarchyResponse, error)
	CheckMembership(context.Context, *CheckMembershipRequest) (*CheckMembershipResponse, error)
	GetUserTenants(context.Context, *GetUserTenantsRequest) (*GetUserTenantsResponse, error)
	// --- Tenant CRUD ---
	CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error)
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteResponse, error)
	// --- Slug ---
	CheckSlugAvailable(context.Context, *CheckSlugAvailableRequest) (*CheckSlugAvailableResponse, error)
	// --- Onboarding ---
	CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*DeleteResponse, error)
	// --- Membership ---
	AddMember(context.Context, *AddMemberRequest) (*DeleteResponse, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*DeleteResponse, error)
	GetTenantMemberUserIds(context.Context, *GetTenantMemberUserIdsRequest) (*GetTenantMemberUserIdsResponse, error)
	// --- Webhook ---
	UpdateTenantWebhook(context.Context, *UpdateTenantWebhookRequest) (*UpdateTenantWebhookResponse, error)
	// --- API Key ---
	RotateApiKey(context.Context, *RotateApiKeyRequest) (*RotateApiKeyResponse, error)
	// --- Rate Limit Profiles ---
	CreateTenantRateLimitProfile(context.Context, *CreateTenantRateLimitProfileRequest) (*RateLimitProfileResponse, error)
	GetTenantRateLimitProfiles(context.Context, *GetTenantRateLimitProfilesRequest) (*GetTenantRateLimitProfilesResponse, error)
	UpdateTenantRateLimitProfile(context.Context, *UpdateTenantRateLimitProfileRequest) (*RateLimitProfileResponse, error)
	DeleteTenantRateLimitProfile(context.Context, *DeleteTenantRateLimitProfileRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedTenantServiceServer()
}

// UnimplementedTenantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantServiceServer struct{}

func (UnimplementedTenantServiceServer) ValidateApiKey(context.Context, *ValidateApiKeyRequest) (*ValidateApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateApiKey not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantPolicy(context.Context, *GetPolicyRequest) (*TenantPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantPolicy not implemented")
}
func (UnimplementedTenantServiceServer) GetTenant(context.Context, *GetTenantRequest) (*TenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantHierarchy(context.Context, *GetTenantHierarchyRequest) (*GetTenantHierarchyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantHierarchy not implemented")
}
func (UnimplementedTenantServiceServer) CheckMembership(context.Context, *CheckMembershipRequest) (*CheckMembershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckMembership not implemented")
}
func (UnimplementedTenantServiceServer) GetUserTenants(context.Context, *GetUserTenantsRequest) (*GetUserTenantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserTenants not implemented")
}
func (UnimplementedTenantServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*CreateTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedTenantServiceServer) DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedTenantServiceServer) CheckSlugAvailable(context.Context, *CheckSlugAvailableRequest) (*CheckSlugAvailableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSlugAvailable not implemented")
}
func (UnimplementedTenantServiceServer) CompleteOnboarding(context.Context, *CompleteOnboardingRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteOnboarding not implemented")
}
func (UnimplementedTenantServiceServer) AddMember(context.Context, *AddMemberRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedTenantServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantMemberUserIds(context.Context, *GetTenantMemberUserIdsRequest) (*GetTenantMemberUserIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantMemberUserIds not implemented")
}
func (UnimplementedTenantServiceServer) UpdateTenantWebhook(context.Context, *UpdateTenantWebhookRequest) (*UpdateTenantWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTenantWebhook not implemented")
}
func (UnimplementedTenantServiceServer) RotateApiKey(context.Context, *RotateApiKeyRequest) (*RotateApiKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateApiKey not implemented")
}
func (UnimplementedTenantServiceServer) CreateTenantRateLimitProfile(context.Context, *CreateTenantRateLimitProfileRequest) (*RateLimitProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenantRateLimitProfile not implemented")
}
func (UnimplementedTenantServiceServer) GetTenantRateLimitProfiles(context.Context, *GetTenantRateLimitProfilesRequest) (*GetTenantRateLimitProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenantRateLimitProfiles not implemented")
}
func (UnimplementedTenantServiceServer) UpdateTenantRateLimitProfile(context.Context, *UpdateTenantRateLimitProfileRequest) (*RateLimitProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTenantRateLimitProfile not implemented")
}
func (UnimplementedTenantServiceServer) DeleteTenantRateLimitProfile(context.Context, *DeleteTenantRateLimitProfileRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTenantRateLimitProfile not implemented")
}
func (UnimplementedTenantServiceServer) mustEmbedUnimplementedTenantServiceServer() {}
func (UnimplementedTenantServiceServer) testEmbeddedByValue()                       {}

// UnsafeTenantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantServiceServer will
// result in compilation errors.
type UnsafeTenantServiceServer interface {
	mustEmbedUnimplementedTenantServiceServer()
}

func RegisterTenantServiceServer(s grpc.ServiceRegistrar, srv TenantServiceServer) {
	// If the following call panics, it indicates UnimplementedTenantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantService_ServiceDesc, srv)
}

func _TenantService_ValidateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).ValidateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_ValidateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).ValidateApiKey(ctx, req.(*ValidateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantHierarchy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantHierarchyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantHierarchy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantHierarchy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantHierarchy(ctx, req.(*GetTenantHierarchyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_CheckMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CheckMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_CheckMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CheckMembership(ctx, req.(*CheckMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetUserTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetUserTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetUserTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetUserTenants(ctx, req.(*GetUserTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).DeleteTenant(ctx, req.(*DeleteTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_CheckSlugAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSlugAvailableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CheckSlugAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_CheckSlugAvailable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CheckSlugAvailable(ctx, req.(*CheckSlugAvailableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_CompleteOnboarding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteOnboardingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CompleteOnboarding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_CompleteOnboarding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CompleteOnboarding(ctx, req.(*CompleteOnboardingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantMemberUserIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantMemberUserIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantMemberUserIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantMemberUserIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantMemberUserIds(ctx, req.(*GetTenantMemberUserIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_UpdateTenantWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).UpdateTenantWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_UpdateTenantWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).UpdateTenantWebhook(ctx, req.(*UpdateTenantWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_RotateApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).RotateApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_RotateApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).RotateApiKey(ctx, req.(*RotateApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_CreateTenantRateLimitProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRateLimitProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).CreateTenantRateLimitProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_CreateTenantRateLimitProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).CreateTenantRateLimitProfile(ctx, req.(*CreateTenantRateLimitProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_GetTenantRateLimitProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRateLimitProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).GetTenantRateLimitProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_GetTenantRateLimitProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).GetTenantRateLimitProfiles(ctx, req.(*GetTenantRateLimitProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_UpdateTenantRateLimitProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantRateLimitProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).UpdateTenantRateLimitProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_UpdateTenantRateLimitProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).UpdateTenantRateLimitProfile(ctx, req.(*UpdateTenantRateLimitProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantService_DeleteTenantRateLimitProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRateLimitProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantServiceServer).DeleteTenantRateLimitProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantService_DeleteTenantRateLimitProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantServiceServer).DeleteTenantRateLimitProfile(ctx, req.(*DeleteTenantRateLimitProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantService_ServiceDesc is the grpc.ServiceDesc for TenantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenant.TenantService",
	HandlerType: (*TenantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateApiKey",
			Handler:    _TenantService_ValidateApiKey_Handler,
		},
		{
			MethodName: "GetTenantPolicy",
			Handler:    _TenantService_GetTenantPolicy_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _TenantService_GetTenant_Handler,
		},
		{
			MethodName: "GetTenantHierarchy",
			Handler:    _TenantService_GetTenantHierarchy_Handler,
		},
		{
			MethodName: "CheckMembership",
			Handler:    _TenantService_CheckMembership_Handler,
		},
		{
			MethodName: "GetUserTenants",
			Handler:    _TenantService_GetUserTenants_Handler,
		},
		{
			MethodName: "CreateTenant",
			Handler:    _TenantService_CreateTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _TenantService_DeleteTenant_Handler,
		},
		{
			MethodName: "CheckSlugAvailable",
			Handler:    _TenantService_CheckSlugAvailable_Handler,
		},
		{
			MethodName: "CompleteOnboarding",
			Handler:    _TenantService_CompleteOnboarding_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _TenantService_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _TenantService_RemoveMember_Handler,
		},
		{
			MethodName: "GetTenantMemberUserIds",
			Handler:    _TenantService_GetTenantMemberUserIds_Handler,
		},
		{
			MethodName: "UpdateTenantWebhook",
			Handler:    _TenantService_UpdateTenantWebhook_Handler,
		},
		{
			MethodName: "RotateApiKey",
			Handler:    _TenantService_RotateApiKey_Handler,
		},
		{
			MethodName: "CreateTenantRateLimitProfile",
			Handler:    _TenantService_CreateTenantRateLimitProfile_Handler,
		},
		{
			MethodName: "GetTenantRateLimitProfiles",
			Handler:    _TenantService_GetTenantRateLimitProfiles_Handler,
		},
		{
			MethodName: "UpdateTenantRateLimitProfile",
			Handler:    _TenantService_UpdateTenantRateLimitProfile_Handler,
		},
		{
			MethodName: "DeleteTenantRateLimitProfile",
			Handler:    _TenantService_DeleteTenantRateLimitProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenant.proto",
}
