# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"\xde\x01\n\x0eRequestContext\x12\x18\n\x07traceId\x18\x01 \x01(\tR\x07traceId\x12$\n\rcorrelationId\x18\x02 \x01(\tR\rcorrelationId\x12\x1a\n\x08tenantId\x18\x03 \x01(\tR\x08tenantId\x12\x16\n\x06userId\x18\x04 \x01(\tR\x06userId\x12\x1c\n\tipAddress\x18\x05 \x01(\tR\tipAddress\x12\x1c\n\tuserAgent\x18\x06 \x01(\tR\tuserAgent\x12\x1c\n\ttimestamp\x18\x07 \x01(\x03R\ttimestamp\"\xb7\x01\n\rErrorResponse\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12<\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\".common.ErrorResponse.DetailsEntryR\x07\x64\x65tails\x1a:\n\x0c\x44\x65tailsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"U\n\x11PaginationRequest\x12\x12\n\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n\x06\x63ursor\x18\x03 \x01(\tR\x06\x63ursor\"\x90\x01\n\x12PaginationResponse\x12\x14\n\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n\x0bnext_cursor\x18\x04 \x01(\tR\nnextCursor\x12\x19\n\x08has_more\x18\x05 \x01(\x08R\x07hasMore\"W\n\x0e\x44\x65leteResponse\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12+\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x15.common.ErrorResponseR\x05\x65rror*r\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n\rSTATUS_ACTIVE\x10\x01\x12\x13\n\x0fSTATUS_INACTIVE\x10\x02\x12\x14\n\x10STATUS_SUSPENDED\x10\x03\x12\x12\n\x0eSTATUS_PENDING\x10\x04\x42r\n\ncom.commonB\x0b\x43ommonProtoP\x01Z\x1fgithub.com/yourorg/sdk/go/proto\xa2\x02\x03\x43XX\xaa\x02\x06\x43ommon\xca\x02\x06\x43ommon\xe2\x02\x12\x43ommon\\GPBMetadata\xea\x02\x06\x43ommonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\ncom.commonB\013CommonProtoP\001Z\037github.com/yourorg/sdk/go/proto\242\002\003CXX\252\002\006Common\312\002\006Common\342\002\022Common\\GPBMetadata\352\002\006Common'
  _globals['_ERRORRESPONSE_DETAILSENTRY']._loaded_options = None
  _globals['_ERRORRESPONSE_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_STATUS']._serialized_start=758
  _globals['_STATUS']._serialized_end=872
  _globals['_REQUESTCONTEXT']._serialized_start=25
  _globals['_REQUESTCONTEXT']._serialized_end=247
  _globals['_ERRORRESPONSE']._serialized_start=250
  _globals['_ERRORRESPONSE']._serialized_end=433
  _globals['_ERRORRESPONSE_DETAILSENTRY']._serialized_start=375
  _globals['_ERRORRESPONSE_DETAILSENTRY']._serialized_end=433
  _globals['_PAGINATIONREQUEST']._serialized_start=435
  _globals['_PAGINATIONREQUEST']._serialized_end=520
  _globals['_PAGINATIONRESPONSE']._serialized_start=523
  _globals['_PAGINATIONRESPONSE']._serialized_end=667
  _globals['_DELETERESPONSE']._serialized_start=669
  _globals['_DELETERESPONSE']._serialized_end=756
# @@protoc_insertion_point(module_scope)
