// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: audit.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Struct } from "./google/protobuf/struct";

export const protobufPackage = "audit";

/** Matches your AuditLog and AuditEvent Prisma models */
export interface AuditLogResponse {
  id: string;
  userId: string;
  tenantId: string;
  action: string;
  resource: string;
  metadata: { [key: string]: any } | undefined;
  timestamp: string;
  ip: string;
  userAgent: string;
  deviceId: string;
  traceId: string;
  correlationId: string;
  severity: string;
  integrityHash: string;
}

export interface LogEventRequest {
  userId: string;
  tenantId: string;
  action: string;
  resource: string;
  metadata: { [key: string]: any } | undefined;
  ip: string;
  userAgent: string;
  deviceId: string;
  traceId: string;
  correlationId: string;
}

export interface LogEventResponse {
  success: boolean;
  eventId: string;
}

export interface GetEventRequest {
  id: string;
}

export interface GetEventsRequest {
  userId: string;
  tenantId: string;
  action: string;
  startDate: string;
  endDate: string;
  limit: number;
  offset: number;
}

export interface GetEventsResponse {
  events: AuditLogResponse[];
  total: number;
}

export interface SearchRequest {
  query: string;
  size: number;
  from: number;
}

export interface SearchResponse {
  results: AuditLogResponse[];
  totalHits: number;
}

export interface AnalyticsRequest {
  days: number;
}

export interface AnalyticsResponse {
  totalSecurityEvents: number;
  timeline: { [key: string]: any } | undefined;
  breakdown: { [key: string]: any } | undefined;
}

function createBaseAuditLogResponse(): AuditLogResponse {
  return {
    id: "",
    userId: "",
    tenantId: "",
    action: "",
    resource: "",
    metadata: undefined,
    timestamp: "",
    ip: "",
    userAgent: "",
    deviceId: "",
    traceId: "",
    correlationId: "",
    severity: "",
    integrityHash: "",
  };
}

export const AuditLogResponse: MessageFns<AuditLogResponse> = {
  encode(message: AuditLogResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.tenantId !== "") {
      writer.uint32(26).string(message.tenantId);
    }
    if (message.action !== "") {
      writer.uint32(34).string(message.action);
    }
    if (message.resource !== "") {
      writer.uint32(42).string(message.resource);
    }
    if (message.metadata !== undefined) {
      Struct.encode(Struct.wrap(message.metadata), writer.uint32(50).fork()).join();
    }
    if (message.timestamp !== "") {
      writer.uint32(58).string(message.timestamp);
    }
    if (message.ip !== "") {
      writer.uint32(66).string(message.ip);
    }
    if (message.userAgent !== "") {
      writer.uint32(74).string(message.userAgent);
    }
    if (message.deviceId !== "") {
      writer.uint32(82).string(message.deviceId);
    }
    if (message.traceId !== "") {
      writer.uint32(90).string(message.traceId);
    }
    if (message.correlationId !== "") {
      writer.uint32(98).string(message.correlationId);
    }
    if (message.severity !== "") {
      writer.uint32(106).string(message.severity);
    }
    if (message.integrityHash !== "") {
      writer.uint32(114).string(message.integrityHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuditLogResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuditLogResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.resource = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.metadata = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.timestamp = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.userAgent = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.traceId = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.severity = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.integrityHash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuditLogResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      resource: isSet(object.resource) ? globalThis.String(object.resource) : "",
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "",
      ip: isSet(object.ip) ? globalThis.String(object.ip) : "",
      userAgent: isSet(object.userAgent) ? globalThis.String(object.userAgent) : "",
      deviceId: isSet(object.deviceId) ? globalThis.String(object.deviceId) : "",
      traceId: isSet(object.traceId) ? globalThis.String(object.traceId) : "",
      correlationId: isSet(object.correlationId) ? globalThis.String(object.correlationId) : "",
      severity: isSet(object.severity) ? globalThis.String(object.severity) : "",
      integrityHash: isSet(object.integrityHash) ? globalThis.String(object.integrityHash) : "",
    };
  },

  toJSON(message: AuditLogResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.resource !== "") {
      obj.resource = message.resource;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.timestamp !== "") {
      obj.timestamp = message.timestamp;
    }
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    if (message.userAgent !== "") {
      obj.userAgent = message.userAgent;
    }
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    if (message.traceId !== "") {
      obj.traceId = message.traceId;
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    if (message.severity !== "") {
      obj.severity = message.severity;
    }
    if (message.integrityHash !== "") {
      obj.integrityHash = message.integrityHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuditLogResponse>, I>>(base?: I): AuditLogResponse {
    return AuditLogResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuditLogResponse>, I>>(object: I): AuditLogResponse {
    const message = createBaseAuditLogResponse();
    message.id = object.id ?? "";
    message.userId = object.userId ?? "";
    message.tenantId = object.tenantId ?? "";
    message.action = object.action ?? "";
    message.resource = object.resource ?? "";
    message.metadata = object.metadata ?? undefined;
    message.timestamp = object.timestamp ?? "";
    message.ip = object.ip ?? "";
    message.userAgent = object.userAgent ?? "";
    message.deviceId = object.deviceId ?? "";
    message.traceId = object.traceId ?? "";
    message.correlationId = object.correlationId ?? "";
    message.severity = object.severity ?? "";
    message.integrityHash = object.integrityHash ?? "";
    return message;
  },
};

function createBaseLogEventRequest(): LogEventRequest {
  return {
    userId: "",
    tenantId: "",
    action: "",
    resource: "",
    metadata: undefined,
    ip: "",
    userAgent: "",
    deviceId: "",
    traceId: "",
    correlationId: "",
  };
}

export const LogEventRequest: MessageFns<LogEventRequest> = {
  encode(message: LogEventRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.action !== "") {
      writer.uint32(26).string(message.action);
    }
    if (message.resource !== "") {
      writer.uint32(34).string(message.resource);
    }
    if (message.metadata !== undefined) {
      Struct.encode(Struct.wrap(message.metadata), writer.uint32(42).fork()).join();
    }
    if (message.ip !== "") {
      writer.uint32(50).string(message.ip);
    }
    if (message.userAgent !== "") {
      writer.uint32(58).string(message.userAgent);
    }
    if (message.deviceId !== "") {
      writer.uint32(66).string(message.deviceId);
    }
    if (message.traceId !== "") {
      writer.uint32(74).string(message.traceId);
    }
    if (message.correlationId !== "") {
      writer.uint32(82).string(message.correlationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogEventRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogEventRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.resource = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.metadata = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.userAgent = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.traceId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.correlationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogEventRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      resource: isSet(object.resource) ? globalThis.String(object.resource) : "",
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      ip: isSet(object.ip) ? globalThis.String(object.ip) : "",
      userAgent: isSet(object.userAgent) ? globalThis.String(object.userAgent) : "",
      deviceId: isSet(object.deviceId) ? globalThis.String(object.deviceId) : "",
      traceId: isSet(object.traceId) ? globalThis.String(object.traceId) : "",
      correlationId: isSet(object.correlationId) ? globalThis.String(object.correlationId) : "",
    };
  },

  toJSON(message: LogEventRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.resource !== "") {
      obj.resource = message.resource;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    if (message.userAgent !== "") {
      obj.userAgent = message.userAgent;
    }
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    if (message.traceId !== "") {
      obj.traceId = message.traceId;
    }
    if (message.correlationId !== "") {
      obj.correlationId = message.correlationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogEventRequest>, I>>(base?: I): LogEventRequest {
    return LogEventRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogEventRequest>, I>>(object: I): LogEventRequest {
    const message = createBaseLogEventRequest();
    message.userId = object.userId ?? "";
    message.tenantId = object.tenantId ?? "";
    message.action = object.action ?? "";
    message.resource = object.resource ?? "";
    message.metadata = object.metadata ?? undefined;
    message.ip = object.ip ?? "";
    message.userAgent = object.userAgent ?? "";
    message.deviceId = object.deviceId ?? "";
    message.traceId = object.traceId ?? "";
    message.correlationId = object.correlationId ?? "";
    return message;
  },
};

function createBaseLogEventResponse(): LogEventResponse {
  return { success: false, eventId: "" };
}

export const LogEventResponse: MessageFns<LogEventResponse> = {
  encode(message: LogEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.eventId !== "") {
      writer.uint32(18).string(message.eventId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogEventResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.eventId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogEventResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      eventId: isSet(object.eventId) ? globalThis.String(object.eventId) : "",
    };
  },

  toJSON(message: LogEventResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.eventId !== "") {
      obj.eventId = message.eventId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogEventResponse>, I>>(base?: I): LogEventResponse {
    return LogEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogEventResponse>, I>>(object: I): LogEventResponse {
    const message = createBaseLogEventResponse();
    message.success = object.success ?? false;
    message.eventId = object.eventId ?? "";
    return message;
  },
};

function createBaseGetEventRequest(): GetEventRequest {
  return { id: "" };
}

export const GetEventRequest: MessageFns<GetEventRequest> = {
  encode(message: GetEventRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetEventRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetEventRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetEventRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetEventRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetEventRequest>, I>>(base?: I): GetEventRequest {
    return GetEventRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetEventRequest>, I>>(object: I): GetEventRequest {
    const message = createBaseGetEventRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetEventsRequest(): GetEventsRequest {
  return { userId: "", tenantId: "", action: "", startDate: "", endDate: "", limit: 0, offset: 0 };
}

export const GetEventsRequest: MessageFns<GetEventsRequest> = {
  encode(message: GetEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.tenantId !== "") {
      writer.uint32(18).string(message.tenantId);
    }
    if (message.action !== "") {
      writer.uint32(26).string(message.action);
    }
    if (message.startDate !== "") {
      writer.uint32(34).string(message.startDate);
    }
    if (message.endDate !== "") {
      writer.uint32(42).string(message.endDate);
    }
    if (message.limit !== 0) {
      writer.uint32(48).int32(message.limit);
    }
    if (message.offset !== 0) {
      writer.uint32(56).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.startDate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.endDate = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetEventsRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      startDate: isSet(object.startDate) ? globalThis.String(object.startDate) : "",
      endDate: isSet(object.endDate) ? globalThis.String(object.endDate) : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
    };
  },

  toJSON(message: GetEventsRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.startDate !== "") {
      obj.startDate = message.startDate;
    }
    if (message.endDate !== "") {
      obj.endDate = message.endDate;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetEventsRequest>, I>>(base?: I): GetEventsRequest {
    return GetEventsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetEventsRequest>, I>>(object: I): GetEventsRequest {
    const message = createBaseGetEventsRequest();
    message.userId = object.userId ?? "";
    message.tenantId = object.tenantId ?? "";
    message.action = object.action ?? "";
    message.startDate = object.startDate ?? "";
    message.endDate = object.endDate ?? "";
    message.limit = object.limit ?? 0;
    message.offset = object.offset ?? 0;
    return message;
  },
};

function createBaseGetEventsResponse(): GetEventsResponse {
  return { events: [], total: 0 };
}

export const GetEventsResponse: MessageFns<GetEventsResponse> = {
  encode(message: GetEventsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.events) {
      AuditLogResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetEventsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetEventsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.events.push(AuditLogResponse.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetEventsResponse {
    return {
      events: globalThis.Array.isArray(object?.events)
        ? object.events.map((e: any) => AuditLogResponse.fromJSON(e))
        : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: GetEventsResponse): unknown {
    const obj: any = {};
    if (message.events?.length) {
      obj.events = message.events.map((e) => AuditLogResponse.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetEventsResponse>, I>>(base?: I): GetEventsResponse {
    return GetEventsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetEventsResponse>, I>>(object: I): GetEventsResponse {
    const message = createBaseGetEventsResponse();
    message.events = object.events?.map((e) => AuditLogResponse.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseSearchRequest(): SearchRequest {
  return { query: "", size: 0, from: 0 };
}

export const SearchRequest: MessageFns<SearchRequest> = {
  encode(message: SearchRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    if (message.size !== 0) {
      writer.uint32(16).int32(message.size);
    }
    if (message.from !== 0) {
      writer.uint32(24).int32(message.from);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.size = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.from = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchRequest {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      from: isSet(object.from) ? globalThis.Number(object.from) : 0,
    };
  },

  toJSON(message: SearchRequest): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.from !== 0) {
      obj.from = Math.round(message.from);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchRequest>, I>>(base?: I): SearchRequest {
    return SearchRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchRequest>, I>>(object: I): SearchRequest {
    const message = createBaseSearchRequest();
    message.query = object.query ?? "";
    message.size = object.size ?? 0;
    message.from = object.from ?? 0;
    return message;
  },
};

function createBaseSearchResponse(): SearchResponse {
  return { results: [], totalHits: 0 };
}

export const SearchResponse: MessageFns<SearchResponse> = {
  encode(message: SearchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.results) {
      AuditLogResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.totalHits !== 0) {
      writer.uint32(16).int32(message.totalHits);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.results.push(AuditLogResponse.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalHits = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchResponse {
    return {
      results: globalThis.Array.isArray(object?.results)
        ? object.results.map((e: any) => AuditLogResponse.fromJSON(e))
        : [],
      totalHits: isSet(object.totalHits) ? globalThis.Number(object.totalHits) : 0,
    };
  },

  toJSON(message: SearchResponse): unknown {
    const obj: any = {};
    if (message.results?.length) {
      obj.results = message.results.map((e) => AuditLogResponse.toJSON(e));
    }
    if (message.totalHits !== 0) {
      obj.totalHits = Math.round(message.totalHits);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchResponse>, I>>(base?: I): SearchResponse {
    return SearchResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchResponse>, I>>(object: I): SearchResponse {
    const message = createBaseSearchResponse();
    message.results = object.results?.map((e) => AuditLogResponse.fromPartial(e)) || [];
    message.totalHits = object.totalHits ?? 0;
    return message;
  },
};

function createBaseAnalyticsRequest(): AnalyticsRequest {
  return { days: 0 };
}

export const AnalyticsRequest: MessageFns<AnalyticsRequest> = {
  encode(message: AnalyticsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.days !== 0) {
      writer.uint32(8).int32(message.days);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnalyticsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnalyticsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.days = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnalyticsRequest {
    return { days: isSet(object.days) ? globalThis.Number(object.days) : 0 };
  },

  toJSON(message: AnalyticsRequest): unknown {
    const obj: any = {};
    if (message.days !== 0) {
      obj.days = Math.round(message.days);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AnalyticsRequest>, I>>(base?: I): AnalyticsRequest {
    return AnalyticsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AnalyticsRequest>, I>>(object: I): AnalyticsRequest {
    const message = createBaseAnalyticsRequest();
    message.days = object.days ?? 0;
    return message;
  },
};

function createBaseAnalyticsResponse(): AnalyticsResponse {
  return { totalSecurityEvents: 0, timeline: undefined, breakdown: undefined };
}

export const AnalyticsResponse: MessageFns<AnalyticsResponse> = {
  encode(message: AnalyticsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalSecurityEvents !== 0) {
      writer.uint32(8).int64(message.totalSecurityEvents);
    }
    if (message.timeline !== undefined) {
      Struct.encode(Struct.wrap(message.timeline), writer.uint32(18).fork()).join();
    }
    if (message.breakdown !== undefined) {
      Struct.encode(Struct.wrap(message.breakdown), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AnalyticsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAnalyticsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalSecurityEvents = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.timeline = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.breakdown = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AnalyticsResponse {
    return {
      totalSecurityEvents: isSet(object.totalSecurityEvents) ? globalThis.Number(object.totalSecurityEvents) : 0,
      timeline: isObject(object.timeline) ? object.timeline : undefined,
      breakdown: isObject(object.breakdown) ? object.breakdown : undefined,
    };
  },

  toJSON(message: AnalyticsResponse): unknown {
    const obj: any = {};
    if (message.totalSecurityEvents !== 0) {
      obj.totalSecurityEvents = Math.round(message.totalSecurityEvents);
    }
    if (message.timeline !== undefined) {
      obj.timeline = message.timeline;
    }
    if (message.breakdown !== undefined) {
      obj.breakdown = message.breakdown;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AnalyticsResponse>, I>>(base?: I): AnalyticsResponse {
    return AnalyticsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AnalyticsResponse>, I>>(object: I): AnalyticsResponse {
    const message = createBaseAnalyticsResponse();
    message.totalSecurityEvents = object.totalSecurityEvents ?? 0;
    message.timeline = object.timeline ?? undefined;
    message.breakdown = object.breakdown ?? undefined;
    return message;
  },
};

export type AuditServiceService = typeof AuditServiceService;
export const AuditServiceService = {
  /** Persistence */
  logEvent: {
    path: "/audit.AuditService/LogEvent" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: LogEventRequest): Buffer => Buffer.from(LogEventRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): LogEventRequest => LogEventRequest.decode(value),
    responseSerialize: (value: LogEventResponse): Buffer => Buffer.from(LogEventResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): LogEventResponse => LogEventResponse.decode(value),
  },
  /** Queries */
  getEvent: {
    path: "/audit.AuditService/GetEvent" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetEventRequest): Buffer => Buffer.from(GetEventRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetEventRequest => GetEventRequest.decode(value),
    responseSerialize: (value: AuditLogResponse): Buffer => Buffer.from(AuditLogResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AuditLogResponse => AuditLogResponse.decode(value),
  },
  getEvents: {
    path: "/audit.AuditService/GetEvents" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetEventsRequest): Buffer => Buffer.from(GetEventsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetEventsRequest => GetEventsRequest.decode(value),
    responseSerialize: (value: GetEventsResponse): Buffer => Buffer.from(GetEventsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetEventsResponse => GetEventsResponse.decode(value),
  },
  searchEvents: {
    path: "/audit.AuditService/SearchEvents" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: SearchRequest): Buffer => Buffer.from(SearchRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SearchRequest => SearchRequest.decode(value),
    responseSerialize: (value: SearchResponse): Buffer => Buffer.from(SearchResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SearchResponse => SearchResponse.decode(value),
  },
  getSecurityAnalytics: {
    path: "/audit.AuditService/GetSecurityAnalytics" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AnalyticsRequest): Buffer => Buffer.from(AnalyticsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AnalyticsRequest => AnalyticsRequest.decode(value),
    responseSerialize: (value: AnalyticsResponse): Buffer => Buffer.from(AnalyticsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AnalyticsResponse => AnalyticsResponse.decode(value),
  },
} as const;

export interface AuditServiceServer extends UntypedServiceImplementation {
  /** Persistence */
  logEvent: handleUnaryCall<LogEventRequest, LogEventResponse>;
  /** Queries */
  getEvent: handleUnaryCall<GetEventRequest, AuditLogResponse>;
  getEvents: handleUnaryCall<GetEventsRequest, GetEventsResponse>;
  searchEvents: handleUnaryCall<SearchRequest, SearchResponse>;
  getSecurityAnalytics: handleUnaryCall<AnalyticsRequest, AnalyticsResponse>;
}

export interface AuditServiceClient extends Client {
  /** Persistence */
  logEvent(
    request: LogEventRequest,
    callback: (error: ServiceError | null, response: LogEventResponse) => void,
  ): ClientUnaryCall;
  logEvent(
    request: LogEventRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: LogEventResponse) => void,
  ): ClientUnaryCall;
  logEvent(
    request: LogEventRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: LogEventResponse) => void,
  ): ClientUnaryCall;
  /** Queries */
  getEvent(
    request: GetEventRequest,
    callback: (error: ServiceError | null, response: AuditLogResponse) => void,
  ): ClientUnaryCall;
  getEvent(
    request: GetEventRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AuditLogResponse) => void,
  ): ClientUnaryCall;
  getEvent(
    request: GetEventRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AuditLogResponse) => void,
  ): ClientUnaryCall;
  getEvents(
    request: GetEventsRequest,
    callback: (error: ServiceError | null, response: GetEventsResponse) => void,
  ): ClientUnaryCall;
  getEvents(
    request: GetEventsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetEventsResponse) => void,
  ): ClientUnaryCall;
  getEvents(
    request: GetEventsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetEventsResponse) => void,
  ): ClientUnaryCall;
  searchEvents(
    request: SearchRequest,
    callback: (error: ServiceError | null, response: SearchResponse) => void,
  ): ClientUnaryCall;
  searchEvents(
    request: SearchRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SearchResponse) => void,
  ): ClientUnaryCall;
  searchEvents(
    request: SearchRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SearchResponse) => void,
  ): ClientUnaryCall;
  getSecurityAnalytics(
    request: AnalyticsRequest,
    callback: (error: ServiceError | null, response: AnalyticsResponse) => void,
  ): ClientUnaryCall;
  getSecurityAnalytics(
    request: AnalyticsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AnalyticsResponse) => void,
  ): ClientUnaryCall;
  getSecurityAnalytics(
    request: AnalyticsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AnalyticsResponse) => void,
  ): ClientUnaryCall;
}

export const AuditServiceClient = makeGenericClientConstructor(
  AuditServiceService,
  "audit.AuditService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AuditServiceClient;
  service: typeof AuditServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
