// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: security.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { ErrorResponse, RequestContext } from "./common";

export const protobufPackage = "security";

/** IP Check */
export interface CheckIPRequest {
  context: RequestContext | undefined;
  ipAddress: string;
}

export interface ValidateAccessRequest {
  context:
    | RequestContext
    | undefined;
  /** The threshold from the Decorator */
  requiredThreshold: number;
  ipAddress: string;
  userAgent: string;
  fingerprintHash: string;
  userId: string;
}

export interface ValidateAccessResponse {
  allowed: boolean;
  riskScore: number;
  reason: string;
  /** e.g., "MFA", "BLOCK", "CHALLENGE" */
  actionRequired: string;
  error: ErrorResponse | undefined;
}

export interface CheckIPResponse {
  allowed: boolean;
  /** 0-100 */
  reputationScore: number;
  /** "active", "blocked", "trusted" */
  status: string;
  isManuallyBlocked: boolean;
  blockedReason: string;
  expiresAt: number;
  error: ErrorResponse | undefined;
}

/** Bot Detection */
export interface DetectBotRequest {
  context: RequestContext | undefined;
  ipAddress: string;
  userAgent: string;
  fingerprintHash: string;
  headers: { [key: string]: string };
}

export interface DetectBotRequest_HeadersEntry {
  key: string;
  value: string;
}

export interface DetectBotResponse {
  isBot: boolean;
  /** 0-100 */
  confidence: number;
  /** "crawler", "scraper", "automation", etc. */
  botType: string;
  reason: string;
  error: ErrorResponse | undefined;
}

/** Device Validation */
export interface ValidateDeviceRequest {
  context: RequestContext | undefined;
  fingerprintHash: string;
  userAgent: string;
  ipAddress: string;
  userId: string;
}

export interface ValidateDeviceResponse {
  trusted: boolean;
  /** 0-100 */
  riskScore: number;
  isNewDevice: boolean;
  isSuspicious: boolean;
  deviceId: string;
  error: ErrorResponse | undefined;
}

/** Incident Reporting */
export interface ReportIncidentRequest {
  context:
    | RequestContext
    | undefined;
  /** "LOGIN_FAIL", "GEO_ANOMALY", etc. */
  eventType: string;
  /** "LOW", "MEDIUM", "HIGH", "CRITICAL" */
  severity: string;
  userId: string;
  tenantId: string;
  details: { [key: string]: string };
}

export interface ReportIncidentRequest_DetailsEntry {
  key: string;
  value: string;
}

export interface ReportIncidentResponse {
  incidentId: string;
  success: boolean;
  error: ErrorResponse | undefined;
}

/** IP Reputation Details */
export interface GetIPReputationRequest {
  context: RequestContext | undefined;
  ipAddress: string;
  includeHistory: boolean;
}

export interface GetIPReputationResponse {
  ip: string;
  score: number;
  status: string;
  firstSeen: number;
  lastActivity: number;
  history: ReputationHistoryEntry[];
  error: ErrorResponse | undefined;
}

export interface ReputationHistoryEntry {
  oldScore: number;
  newScore: number;
  reason: string;
  timestamp: number;
}

function createBaseCheckIPRequest(): CheckIPRequest {
  return { context: undefined, ipAddress: "" };
}

export const CheckIPRequest: MessageFns<CheckIPRequest> = {
  encode(message: CheckIPRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.ipAddress !== "") {
      writer.uint32(18).string(message.ipAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckIPRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckIPRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ipAddress = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckIPRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      ipAddress: isSet(object.ipAddress)
        ? globalThis.String(object.ipAddress)
        : isSet(object.ip_address)
        ? globalThis.String(object.ip_address)
        : "",
    };
  },

  toJSON(message: CheckIPRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.ipAddress !== "") {
      obj.ipAddress = message.ipAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckIPRequest>, I>>(base?: I): CheckIPRequest {
    return CheckIPRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckIPRequest>, I>>(object: I): CheckIPRequest {
    const message = createBaseCheckIPRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.ipAddress = object.ipAddress ?? "";
    return message;
  },
};

function createBaseValidateAccessRequest(): ValidateAccessRequest {
  return { context: undefined, requiredThreshold: 0, ipAddress: "", userAgent: "", fingerprintHash: "", userId: "" };
}

export const ValidateAccessRequest: MessageFns<ValidateAccessRequest> = {
  encode(message: ValidateAccessRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.requiredThreshold !== 0) {
      writer.uint32(16).int32(message.requiredThreshold);
    }
    if (message.ipAddress !== "") {
      writer.uint32(26).string(message.ipAddress);
    }
    if (message.userAgent !== "") {
      writer.uint32(34).string(message.userAgent);
    }
    if (message.fingerprintHash !== "") {
      writer.uint32(42).string(message.fingerprintHash);
    }
    if (message.userId !== "") {
      writer.uint32(50).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateAccessRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateAccessRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.requiredThreshold = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ipAddress = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userAgent = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.fingerprintHash = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateAccessRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      requiredThreshold: isSet(object.requiredThreshold)
        ? globalThis.Number(object.requiredThreshold)
        : isSet(object.required_threshold)
        ? globalThis.Number(object.required_threshold)
        : 0,
      ipAddress: isSet(object.ipAddress)
        ? globalThis.String(object.ipAddress)
        : isSet(object.ip_address)
        ? globalThis.String(object.ip_address)
        : "",
      userAgent: isSet(object.userAgent)
        ? globalThis.String(object.userAgent)
        : isSet(object.user_agent)
        ? globalThis.String(object.user_agent)
        : "",
      fingerprintHash: isSet(object.fingerprintHash)
        ? globalThis.String(object.fingerprintHash)
        : isSet(object.fingerprint_hash)
        ? globalThis.String(object.fingerprint_hash)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
    };
  },

  toJSON(message: ValidateAccessRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.requiredThreshold !== 0) {
      obj.requiredThreshold = Math.round(message.requiredThreshold);
    }
    if (message.ipAddress !== "") {
      obj.ipAddress = message.ipAddress;
    }
    if (message.userAgent !== "") {
      obj.userAgent = message.userAgent;
    }
    if (message.fingerprintHash !== "") {
      obj.fingerprintHash = message.fingerprintHash;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateAccessRequest>, I>>(base?: I): ValidateAccessRequest {
    return ValidateAccessRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateAccessRequest>, I>>(object: I): ValidateAccessRequest {
    const message = createBaseValidateAccessRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.requiredThreshold = object.requiredThreshold ?? 0;
    message.ipAddress = object.ipAddress ?? "";
    message.userAgent = object.userAgent ?? "";
    message.fingerprintHash = object.fingerprintHash ?? "";
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseValidateAccessResponse(): ValidateAccessResponse {
  return { allowed: false, riskScore: 0, reason: "", actionRequired: "", error: undefined };
}

export const ValidateAccessResponse: MessageFns<ValidateAccessResponse> = {
  encode(message: ValidateAccessResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allowed !== false) {
      writer.uint32(8).bool(message.allowed);
    }
    if (message.riskScore !== 0) {
      writer.uint32(16).int32(message.riskScore);
    }
    if (message.reason !== "") {
      writer.uint32(26).string(message.reason);
    }
    if (message.actionRequired !== "") {
      writer.uint32(34).string(message.actionRequired);
    }
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateAccessResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateAccessResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.allowed = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.riskScore = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.actionRequired = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateAccessResponse {
    return {
      allowed: isSet(object.allowed) ? globalThis.Boolean(object.allowed) : false,
      riskScore: isSet(object.riskScore)
        ? globalThis.Number(object.riskScore)
        : isSet(object.risk_score)
        ? globalThis.Number(object.risk_score)
        : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      actionRequired: isSet(object.actionRequired)
        ? globalThis.String(object.actionRequired)
        : isSet(object.action_required)
        ? globalThis.String(object.action_required)
        : "",
      error: isSet(object.error) ? ErrorResponse.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ValidateAccessResponse): unknown {
    const obj: any = {};
    if (message.allowed !== false) {
      obj.allowed = message.allowed;
    }
    if (message.riskScore !== 0) {
      obj.riskScore = Math.round(message.riskScore);
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.actionRequired !== "") {
      obj.actionRequired = message.actionRequired;
    }
    if (message.error !== undefined) {
      obj.error = ErrorResponse.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateAccessResponse>, I>>(base?: I): ValidateAccessResponse {
    return ValidateAccessResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateAccessResponse>, I>>(object: I): ValidateAccessResponse {
    const message = createBaseValidateAccessResponse();
    message.allowed = object.allowed ?? false;
    message.riskScore = object.riskScore ?? 0;
    message.reason = object.reason ?? "";
    message.actionRequired = object.actionRequired ?? "";
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseCheckIPResponse(): CheckIPResponse {
  return {
    allowed: false,
    reputationScore: 0,
    status: "",
    isManuallyBlocked: false,
    blockedReason: "",
    expiresAt: 0,
    error: undefined,
  };
}

export const CheckIPResponse: MessageFns<CheckIPResponse> = {
  encode(message: CheckIPResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allowed !== false) {
      writer.uint32(8).bool(message.allowed);
    }
    if (message.reputationScore !== 0) {
      writer.uint32(16).int32(message.reputationScore);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    if (message.isManuallyBlocked !== false) {
      writer.uint32(32).bool(message.isManuallyBlocked);
    }
    if (message.blockedReason !== "") {
      writer.uint32(42).string(message.blockedReason);
    }
    if (message.expiresAt !== 0) {
      writer.uint32(48).int64(message.expiresAt);
    }
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckIPResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckIPResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.allowed = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.reputationScore = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isManuallyBlocked = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.blockedReason = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.expiresAt = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckIPResponse {
    return {
      allowed: isSet(object.allowed) ? globalThis.Boolean(object.allowed) : false,
      reputationScore: isSet(object.reputationScore)
        ? globalThis.Number(object.reputationScore)
        : isSet(object.reputation_score)
        ? globalThis.Number(object.reputation_score)
        : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      isManuallyBlocked: isSet(object.isManuallyBlocked)
        ? globalThis.Boolean(object.isManuallyBlocked)
        : isSet(object.is_manually_blocked)
        ? globalThis.Boolean(object.is_manually_blocked)
        : false,
      blockedReason: isSet(object.blockedReason)
        ? globalThis.String(object.blockedReason)
        : isSet(object.blocked_reason)
        ? globalThis.String(object.blocked_reason)
        : "",
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
      error: isSet(object.error) ? ErrorResponse.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: CheckIPResponse): unknown {
    const obj: any = {};
    if (message.allowed !== false) {
      obj.allowed = message.allowed;
    }
    if (message.reputationScore !== 0) {
      obj.reputationScore = Math.round(message.reputationScore);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.isManuallyBlocked !== false) {
      obj.isManuallyBlocked = message.isManuallyBlocked;
    }
    if (message.blockedReason !== "") {
      obj.blockedReason = message.blockedReason;
    }
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    if (message.error !== undefined) {
      obj.error = ErrorResponse.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckIPResponse>, I>>(base?: I): CheckIPResponse {
    return CheckIPResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckIPResponse>, I>>(object: I): CheckIPResponse {
    const message = createBaseCheckIPResponse();
    message.allowed = object.allowed ?? false;
    message.reputationScore = object.reputationScore ?? 0;
    message.status = object.status ?? "";
    message.isManuallyBlocked = object.isManuallyBlocked ?? false;
    message.blockedReason = object.blockedReason ?? "";
    message.expiresAt = object.expiresAt ?? 0;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseDetectBotRequest(): DetectBotRequest {
  return { context: undefined, ipAddress: "", userAgent: "", fingerprintHash: "", headers: {} };
}

export const DetectBotRequest: MessageFns<DetectBotRequest> = {
  encode(message: DetectBotRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.ipAddress !== "") {
      writer.uint32(18).string(message.ipAddress);
    }
    if (message.userAgent !== "") {
      writer.uint32(26).string(message.userAgent);
    }
    if (message.fingerprintHash !== "") {
      writer.uint32(34).string(message.fingerprintHash);
    }
    globalThis.Object.entries(message.headers).forEach(([key, value]: [string, string]) => {
      DetectBotRequest_HeadersEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectBotRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectBotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ipAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userAgent = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.fingerprintHash = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = DetectBotRequest_HeadersEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.headers[entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectBotRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      ipAddress: isSet(object.ipAddress)
        ? globalThis.String(object.ipAddress)
        : isSet(object.ip_address)
        ? globalThis.String(object.ip_address)
        : "",
      userAgent: isSet(object.userAgent)
        ? globalThis.String(object.userAgent)
        : isSet(object.user_agent)
        ? globalThis.String(object.user_agent)
        : "",
      fingerprintHash: isSet(object.fingerprintHash)
        ? globalThis.String(object.fingerprintHash)
        : isSet(object.fingerprint_hash)
        ? globalThis.String(object.fingerprint_hash)
        : "",
      headers: isObject(object.headers)
        ? (globalThis.Object.entries(object.headers) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: DetectBotRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.ipAddress !== "") {
      obj.ipAddress = message.ipAddress;
    }
    if (message.userAgent !== "") {
      obj.userAgent = message.userAgent;
    }
    if (message.fingerprintHash !== "") {
      obj.fingerprintHash = message.fingerprintHash;
    }
    if (message.headers) {
      const entries = globalThis.Object.entries(message.headers) as [string, string][];
      if (entries.length > 0) {
        obj.headers = {};
        entries.forEach(([k, v]) => {
          obj.headers[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectBotRequest>, I>>(base?: I): DetectBotRequest {
    return DetectBotRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectBotRequest>, I>>(object: I): DetectBotRequest {
    const message = createBaseDetectBotRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.ipAddress = object.ipAddress ?? "";
    message.userAgent = object.userAgent ?? "";
    message.fingerprintHash = object.fingerprintHash ?? "";
    message.headers = (globalThis.Object.entries(object.headers ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDetectBotRequest_HeadersEntry(): DetectBotRequest_HeadersEntry {
  return { key: "", value: "" };
}

export const DetectBotRequest_HeadersEntry: MessageFns<DetectBotRequest_HeadersEntry> = {
  encode(message: DetectBotRequest_HeadersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectBotRequest_HeadersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectBotRequest_HeadersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectBotRequest_HeadersEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: DetectBotRequest_HeadersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectBotRequest_HeadersEntry>, I>>(base?: I): DetectBotRequest_HeadersEntry {
    return DetectBotRequest_HeadersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectBotRequest_HeadersEntry>, I>>(
    object: I,
  ): DetectBotRequest_HeadersEntry {
    const message = createBaseDetectBotRequest_HeadersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseDetectBotResponse(): DetectBotResponse {
  return { isBot: false, confidence: 0, botType: "", reason: "", error: undefined };
}

export const DetectBotResponse: MessageFns<DetectBotResponse> = {
  encode(message: DetectBotResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.isBot !== false) {
      writer.uint32(8).bool(message.isBot);
    }
    if (message.confidence !== 0) {
      writer.uint32(16).int32(message.confidence);
    }
    if (message.botType !== "") {
      writer.uint32(26).string(message.botType);
    }
    if (message.reason !== "") {
      writer.uint32(34).string(message.reason);
    }
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DetectBotResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDetectBotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.isBot = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.confidence = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.botType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DetectBotResponse {
    return {
      isBot: isSet(object.isBot)
        ? globalThis.Boolean(object.isBot)
        : isSet(object.is_bot)
        ? globalThis.Boolean(object.is_bot)
        : false,
      confidence: isSet(object.confidence) ? globalThis.Number(object.confidence) : 0,
      botType: isSet(object.botType)
        ? globalThis.String(object.botType)
        : isSet(object.bot_type)
        ? globalThis.String(object.bot_type)
        : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      error: isSet(object.error) ? ErrorResponse.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: DetectBotResponse): unknown {
    const obj: any = {};
    if (message.isBot !== false) {
      obj.isBot = message.isBot;
    }
    if (message.confidence !== 0) {
      obj.confidence = Math.round(message.confidence);
    }
    if (message.botType !== "") {
      obj.botType = message.botType;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.error !== undefined) {
      obj.error = ErrorResponse.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DetectBotResponse>, I>>(base?: I): DetectBotResponse {
    return DetectBotResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DetectBotResponse>, I>>(object: I): DetectBotResponse {
    const message = createBaseDetectBotResponse();
    message.isBot = object.isBot ?? false;
    message.confidence = object.confidence ?? 0;
    message.botType = object.botType ?? "";
    message.reason = object.reason ?? "";
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseValidateDeviceRequest(): ValidateDeviceRequest {
  return { context: undefined, fingerprintHash: "", userAgent: "", ipAddress: "", userId: "" };
}

export const ValidateDeviceRequest: MessageFns<ValidateDeviceRequest> = {
  encode(message: ValidateDeviceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.fingerprintHash !== "") {
      writer.uint32(18).string(message.fingerprintHash);
    }
    if (message.userAgent !== "") {
      writer.uint32(26).string(message.userAgent);
    }
    if (message.ipAddress !== "") {
      writer.uint32(34).string(message.ipAddress);
    }
    if (message.userId !== "") {
      writer.uint32(42).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateDeviceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateDeviceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fingerprintHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userAgent = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ipAddress = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateDeviceRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      fingerprintHash: isSet(object.fingerprintHash)
        ? globalThis.String(object.fingerprintHash)
        : isSet(object.fingerprint_hash)
        ? globalThis.String(object.fingerprint_hash)
        : "",
      userAgent: isSet(object.userAgent)
        ? globalThis.String(object.userAgent)
        : isSet(object.user_agent)
        ? globalThis.String(object.user_agent)
        : "",
      ipAddress: isSet(object.ipAddress)
        ? globalThis.String(object.ipAddress)
        : isSet(object.ip_address)
        ? globalThis.String(object.ip_address)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
    };
  },

  toJSON(message: ValidateDeviceRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.fingerprintHash !== "") {
      obj.fingerprintHash = message.fingerprintHash;
    }
    if (message.userAgent !== "") {
      obj.userAgent = message.userAgent;
    }
    if (message.ipAddress !== "") {
      obj.ipAddress = message.ipAddress;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateDeviceRequest>, I>>(base?: I): ValidateDeviceRequest {
    return ValidateDeviceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateDeviceRequest>, I>>(object: I): ValidateDeviceRequest {
    const message = createBaseValidateDeviceRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.fingerprintHash = object.fingerprintHash ?? "";
    message.userAgent = object.userAgent ?? "";
    message.ipAddress = object.ipAddress ?? "";
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseValidateDeviceResponse(): ValidateDeviceResponse {
  return { trusted: false, riskScore: 0, isNewDevice: false, isSuspicious: false, deviceId: "", error: undefined };
}

export const ValidateDeviceResponse: MessageFns<ValidateDeviceResponse> = {
  encode(message: ValidateDeviceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trusted !== false) {
      writer.uint32(8).bool(message.trusted);
    }
    if (message.riskScore !== 0) {
      writer.uint32(16).int32(message.riskScore);
    }
    if (message.isNewDevice !== false) {
      writer.uint32(24).bool(message.isNewDevice);
    }
    if (message.isSuspicious !== false) {
      writer.uint32(32).bool(message.isSuspicious);
    }
    if (message.deviceId !== "") {
      writer.uint32(42).string(message.deviceId);
    }
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateDeviceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateDeviceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.trusted = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.riskScore = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isNewDevice = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isSuspicious = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.deviceId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateDeviceResponse {
    return {
      trusted: isSet(object.trusted) ? globalThis.Boolean(object.trusted) : false,
      riskScore: isSet(object.riskScore)
        ? globalThis.Number(object.riskScore)
        : isSet(object.risk_score)
        ? globalThis.Number(object.risk_score)
        : 0,
      isNewDevice: isSet(object.isNewDevice)
        ? globalThis.Boolean(object.isNewDevice)
        : isSet(object.is_new_device)
        ? globalThis.Boolean(object.is_new_device)
        : false,
      isSuspicious: isSet(object.isSuspicious)
        ? globalThis.Boolean(object.isSuspicious)
        : isSet(object.is_suspicious)
        ? globalThis.Boolean(object.is_suspicious)
        : false,
      deviceId: isSet(object.deviceId)
        ? globalThis.String(object.deviceId)
        : isSet(object.device_id)
        ? globalThis.String(object.device_id)
        : "",
      error: isSet(object.error) ? ErrorResponse.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ValidateDeviceResponse): unknown {
    const obj: any = {};
    if (message.trusted !== false) {
      obj.trusted = message.trusted;
    }
    if (message.riskScore !== 0) {
      obj.riskScore = Math.round(message.riskScore);
    }
    if (message.isNewDevice !== false) {
      obj.isNewDevice = message.isNewDevice;
    }
    if (message.isSuspicious !== false) {
      obj.isSuspicious = message.isSuspicious;
    }
    if (message.deviceId !== "") {
      obj.deviceId = message.deviceId;
    }
    if (message.error !== undefined) {
      obj.error = ErrorResponse.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateDeviceResponse>, I>>(base?: I): ValidateDeviceResponse {
    return ValidateDeviceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateDeviceResponse>, I>>(object: I): ValidateDeviceResponse {
    const message = createBaseValidateDeviceResponse();
    message.trusted = object.trusted ?? false;
    message.riskScore = object.riskScore ?? 0;
    message.isNewDevice = object.isNewDevice ?? false;
    message.isSuspicious = object.isSuspicious ?? false;
    message.deviceId = object.deviceId ?? "";
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseReportIncidentRequest(): ReportIncidentRequest {
  return { context: undefined, eventType: "", severity: "", userId: "", tenantId: "", details: {} };
}

export const ReportIncidentRequest: MessageFns<ReportIncidentRequest> = {
  encode(message: ReportIncidentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.eventType !== "") {
      writer.uint32(18).string(message.eventType);
    }
    if (message.severity !== "") {
      writer.uint32(26).string(message.severity);
    }
    if (message.userId !== "") {
      writer.uint32(34).string(message.userId);
    }
    if (message.tenantId !== "") {
      writer.uint32(42).string(message.tenantId);
    }
    globalThis.Object.entries(message.details).forEach(([key, value]: [string, string]) => {
      ReportIncidentRequest_DetailsEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReportIncidentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReportIncidentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.eventType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.severity = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = ReportIncidentRequest_DetailsEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.details[entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReportIncidentRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      eventType: isSet(object.eventType)
        ? globalThis.String(object.eventType)
        : isSet(object.event_type)
        ? globalThis.String(object.event_type)
        : "",
      severity: isSet(object.severity) ? globalThis.String(object.severity) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      tenantId: isSet(object.tenantId)
        ? globalThis.String(object.tenantId)
        : isSet(object.tenant_id)
        ? globalThis.String(object.tenant_id)
        : "",
      details: isObject(object.details)
        ? (globalThis.Object.entries(object.details) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ReportIncidentRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.eventType !== "") {
      obj.eventType = message.eventType;
    }
    if (message.severity !== "") {
      obj.severity = message.severity;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.details) {
      const entries = globalThis.Object.entries(message.details) as [string, string][];
      if (entries.length > 0) {
        obj.details = {};
        entries.forEach(([k, v]) => {
          obj.details[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReportIncidentRequest>, I>>(base?: I): ReportIncidentRequest {
    return ReportIncidentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReportIncidentRequest>, I>>(object: I): ReportIncidentRequest {
    const message = createBaseReportIncidentRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.eventType = object.eventType ?? "";
    message.severity = object.severity ?? "";
    message.userId = object.userId ?? "";
    message.tenantId = object.tenantId ?? "";
    message.details = (globalThis.Object.entries(object.details ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseReportIncidentRequest_DetailsEntry(): ReportIncidentRequest_DetailsEntry {
  return { key: "", value: "" };
}

export const ReportIncidentRequest_DetailsEntry: MessageFns<ReportIncidentRequest_DetailsEntry> = {
  encode(message: ReportIncidentRequest_DetailsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReportIncidentRequest_DetailsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReportIncidentRequest_DetailsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReportIncidentRequest_DetailsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ReportIncidentRequest_DetailsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReportIncidentRequest_DetailsEntry>, I>>(
    base?: I,
  ): ReportIncidentRequest_DetailsEntry {
    return ReportIncidentRequest_DetailsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReportIncidentRequest_DetailsEntry>, I>>(
    object: I,
  ): ReportIncidentRequest_DetailsEntry {
    const message = createBaseReportIncidentRequest_DetailsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseReportIncidentResponse(): ReportIncidentResponse {
  return { incidentId: "", success: false, error: undefined };
}

export const ReportIncidentResponse: MessageFns<ReportIncidentResponse> = {
  encode(message: ReportIncidentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.incidentId !== "") {
      writer.uint32(10).string(message.incidentId);
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReportIncidentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReportIncidentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.incidentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReportIncidentResponse {
    return {
      incidentId: isSet(object.incidentId)
        ? globalThis.String(object.incidentId)
        : isSet(object.incident_id)
        ? globalThis.String(object.incident_id)
        : "",
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      error: isSet(object.error) ? ErrorResponse.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: ReportIncidentResponse): unknown {
    const obj: any = {};
    if (message.incidentId !== "") {
      obj.incidentId = message.incidentId;
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.error !== undefined) {
      obj.error = ErrorResponse.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReportIncidentResponse>, I>>(base?: I): ReportIncidentResponse {
    return ReportIncidentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReportIncidentResponse>, I>>(object: I): ReportIncidentResponse {
    const message = createBaseReportIncidentResponse();
    message.incidentId = object.incidentId ?? "";
    message.success = object.success ?? false;
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseGetIPReputationRequest(): GetIPReputationRequest {
  return { context: undefined, ipAddress: "", includeHistory: false };
}

export const GetIPReputationRequest: MessageFns<GetIPReputationRequest> = {
  encode(message: GetIPReputationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    if (message.ipAddress !== "") {
      writer.uint32(18).string(message.ipAddress);
    }
    if (message.includeHistory !== false) {
      writer.uint32(24).bool(message.includeHistory);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetIPReputationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetIPReputationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ipAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.includeHistory = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetIPReputationRequest {
    return {
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
      ipAddress: isSet(object.ipAddress)
        ? globalThis.String(object.ipAddress)
        : isSet(object.ip_address)
        ? globalThis.String(object.ip_address)
        : "",
      includeHistory: isSet(object.includeHistory)
        ? globalThis.Boolean(object.includeHistory)
        : isSet(object.include_history)
        ? globalThis.Boolean(object.include_history)
        : false,
    };
  },

  toJSON(message: GetIPReputationRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    if (message.ipAddress !== "") {
      obj.ipAddress = message.ipAddress;
    }
    if (message.includeHistory !== false) {
      obj.includeHistory = message.includeHistory;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetIPReputationRequest>, I>>(base?: I): GetIPReputationRequest {
    return GetIPReputationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetIPReputationRequest>, I>>(object: I): GetIPReputationRequest {
    const message = createBaseGetIPReputationRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    message.ipAddress = object.ipAddress ?? "";
    message.includeHistory = object.includeHistory ?? false;
    return message;
  },
};

function createBaseGetIPReputationResponse(): GetIPReputationResponse {
  return { ip: "", score: 0, status: "", firstSeen: 0, lastActivity: 0, history: [], error: undefined };
}

export const GetIPReputationResponse: MessageFns<GetIPReputationResponse> = {
  encode(message: GetIPReputationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ip !== "") {
      writer.uint32(10).string(message.ip);
    }
    if (message.score !== 0) {
      writer.uint32(16).int32(message.score);
    }
    if (message.status !== "") {
      writer.uint32(26).string(message.status);
    }
    if (message.firstSeen !== 0) {
      writer.uint32(32).int64(message.firstSeen);
    }
    if (message.lastActivity !== 0) {
      writer.uint32(40).int64(message.lastActivity);
    }
    for (const v of message.history) {
      ReputationHistoryEntry.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetIPReputationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetIPReputationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ip = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.score = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.firstSeen = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.lastActivity = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.history.push(ReputationHistoryEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetIPReputationResponse {
    return {
      ip: isSet(object.ip) ? globalThis.String(object.ip) : "",
      score: isSet(object.score) ? globalThis.Number(object.score) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      firstSeen: isSet(object.firstSeen)
        ? globalThis.Number(object.firstSeen)
        : isSet(object.first_seen)
        ? globalThis.Number(object.first_seen)
        : 0,
      lastActivity: isSet(object.lastActivity)
        ? globalThis.Number(object.lastActivity)
        : isSet(object.last_activity)
        ? globalThis.Number(object.last_activity)
        : 0,
      history: globalThis.Array.isArray(object?.history)
        ? object.history.map((e: any) => ReputationHistoryEntry.fromJSON(e))
        : [],
      error: isSet(object.error) ? ErrorResponse.fromJSON(object.error) : undefined,
    };
  },

  toJSON(message: GetIPReputationResponse): unknown {
    const obj: any = {};
    if (message.ip !== "") {
      obj.ip = message.ip;
    }
    if (message.score !== 0) {
      obj.score = Math.round(message.score);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.firstSeen !== 0) {
      obj.firstSeen = Math.round(message.firstSeen);
    }
    if (message.lastActivity !== 0) {
      obj.lastActivity = Math.round(message.lastActivity);
    }
    if (message.history?.length) {
      obj.history = message.history.map((e) => ReputationHistoryEntry.toJSON(e));
    }
    if (message.error !== undefined) {
      obj.error = ErrorResponse.toJSON(message.error);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetIPReputationResponse>, I>>(base?: I): GetIPReputationResponse {
    return GetIPReputationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetIPReputationResponse>, I>>(object: I): GetIPReputationResponse {
    const message = createBaseGetIPReputationResponse();
    message.ip = object.ip ?? "";
    message.score = object.score ?? 0;
    message.status = object.status ?? "";
    message.firstSeen = object.firstSeen ?? 0;
    message.lastActivity = object.lastActivity ?? 0;
    message.history = object.history?.map((e) => ReputationHistoryEntry.fromPartial(e)) || [];
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    return message;
  },
};

function createBaseReputationHistoryEntry(): ReputationHistoryEntry {
  return { oldScore: 0, newScore: 0, reason: "", timestamp: 0 };
}

export const ReputationHistoryEntry: MessageFns<ReputationHistoryEntry> = {
  encode(message: ReputationHistoryEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.oldScore !== 0) {
      writer.uint32(8).int32(message.oldScore);
    }
    if (message.newScore !== 0) {
      writer.uint32(16).int32(message.newScore);
    }
    if (message.reason !== "") {
      writer.uint32(26).string(message.reason);
    }
    if (message.timestamp !== 0) {
      writer.uint32(32).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReputationHistoryEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReputationHistoryEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.oldScore = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.newScore = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReputationHistoryEntry {
    return {
      oldScore: isSet(object.oldScore)
        ? globalThis.Number(object.oldScore)
        : isSet(object.old_score)
        ? globalThis.Number(object.old_score)
        : 0,
      newScore: isSet(object.newScore)
        ? globalThis.Number(object.newScore)
        : isSet(object.new_score)
        ? globalThis.Number(object.new_score)
        : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: ReputationHistoryEntry): unknown {
    const obj: any = {};
    if (message.oldScore !== 0) {
      obj.oldScore = Math.round(message.oldScore);
    }
    if (message.newScore !== 0) {
      obj.newScore = Math.round(message.newScore);
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReputationHistoryEntry>, I>>(base?: I): ReputationHistoryEntry {
    return ReputationHistoryEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReputationHistoryEntry>, I>>(object: I): ReputationHistoryEntry {
    const message = createBaseReputationHistoryEntry();
    message.oldScore = object.oldScore ?? 0;
    message.newScore = object.newScore ?? 0;
    message.reason = object.reason ?? "";
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

export type SecurityServiceService = typeof SecurityServiceService;
export const SecurityServiceService = {
  /**
   * NEW: Unified Access Validation
   * This combines IP, Bot, Device, and Behavioral analysis in one fast call
   */
  validateAccess: {
    path: "/security.SecurityService/ValidateAccess" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ValidateAccessRequest): Buffer =>
      Buffer.from(ValidateAccessRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ValidateAccessRequest => ValidateAccessRequest.decode(value),
    responseSerialize: (value: ValidateAccessResponse): Buffer =>
      Buffer.from(ValidateAccessResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ValidateAccessResponse => ValidateAccessResponse.decode(value),
  },
  /** IP reputation check - called by Gateway */
  checkIp: {
    path: "/security.SecurityService/CheckIP" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckIPRequest): Buffer => Buffer.from(CheckIPRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckIPRequest => CheckIPRequest.decode(value),
    responseSerialize: (value: CheckIPResponse): Buffer => Buffer.from(CheckIPResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckIPResponse => CheckIPResponse.decode(value),
  },
  /** Bot detection */
  detectBot: {
    path: "/security.SecurityService/DetectBot" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DetectBotRequest): Buffer => Buffer.from(DetectBotRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DetectBotRequest => DetectBotRequest.decode(value),
    responseSerialize: (value: DetectBotResponse): Buffer => Buffer.from(DetectBotResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DetectBotResponse => DetectBotResponse.decode(value),
  },
  /** Device fingerprint validation */
  validateDevice: {
    path: "/security.SecurityService/ValidateDevice" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ValidateDeviceRequest): Buffer =>
      Buffer.from(ValidateDeviceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ValidateDeviceRequest => ValidateDeviceRequest.decode(value),
    responseSerialize: (value: ValidateDeviceResponse): Buffer =>
      Buffer.from(ValidateDeviceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ValidateDeviceResponse => ValidateDeviceResponse.decode(value),
  },
  /** Report security incident */
  reportIncident: {
    path: "/security.SecurityService/ReportIncident" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ReportIncidentRequest): Buffer =>
      Buffer.from(ReportIncidentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ReportIncidentRequest => ReportIncidentRequest.decode(value),
    responseSerialize: (value: ReportIncidentResponse): Buffer =>
      Buffer.from(ReportIncidentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ReportIncidentResponse => ReportIncidentResponse.decode(value),
  },
  /** Get IP reputation details */
  getIpReputation: {
    path: "/security.SecurityService/GetIPReputation" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetIPReputationRequest): Buffer =>
      Buffer.from(GetIPReputationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetIPReputationRequest => GetIPReputationRequest.decode(value),
    responseSerialize: (value: GetIPReputationResponse): Buffer =>
      Buffer.from(GetIPReputationResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetIPReputationResponse => GetIPReputationResponse.decode(value),
  },
} as const;

export interface SecurityServiceServer extends UntypedServiceImplementation {
  /**
   * NEW: Unified Access Validation
   * This combines IP, Bot, Device, and Behavioral analysis in one fast call
   */
  validateAccess: handleUnaryCall<ValidateAccessRequest, ValidateAccessResponse>;
  /** IP reputation check - called by Gateway */
  checkIp: handleUnaryCall<CheckIPRequest, CheckIPResponse>;
  /** Bot detection */
  detectBot: handleUnaryCall<DetectBotRequest, DetectBotResponse>;
  /** Device fingerprint validation */
  validateDevice: handleUnaryCall<ValidateDeviceRequest, ValidateDeviceResponse>;
  /** Report security incident */
  reportIncident: handleUnaryCall<ReportIncidentRequest, ReportIncidentResponse>;
  /** Get IP reputation details */
  getIpReputation: handleUnaryCall<GetIPReputationRequest, GetIPReputationResponse>;
}

export interface SecurityServiceClient extends Client {
  /**
   * NEW: Unified Access Validation
   * This combines IP, Bot, Device, and Behavioral analysis in one fast call
   */
  validateAccess(
    request: ValidateAccessRequest,
    callback: (error: ServiceError | null, response: ValidateAccessResponse) => void,
  ): ClientUnaryCall;
  validateAccess(
    request: ValidateAccessRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ValidateAccessResponse) => void,
  ): ClientUnaryCall;
  validateAccess(
    request: ValidateAccessRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ValidateAccessResponse) => void,
  ): ClientUnaryCall;
  /** IP reputation check - called by Gateway */
  checkIp(
    request: CheckIPRequest,
    callback: (error: ServiceError | null, response: CheckIPResponse) => void,
  ): ClientUnaryCall;
  checkIp(
    request: CheckIPRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CheckIPResponse) => void,
  ): ClientUnaryCall;
  checkIp(
    request: CheckIPRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CheckIPResponse) => void,
  ): ClientUnaryCall;
  /** Bot detection */
  detectBot(
    request: DetectBotRequest,
    callback: (error: ServiceError | null, response: DetectBotResponse) => void,
  ): ClientUnaryCall;
  detectBot(
    request: DetectBotRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DetectBotResponse) => void,
  ): ClientUnaryCall;
  detectBot(
    request: DetectBotRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DetectBotResponse) => void,
  ): ClientUnaryCall;
  /** Device fingerprint validation */
  validateDevice(
    request: ValidateDeviceRequest,
    callback: (error: ServiceError | null, response: ValidateDeviceResponse) => void,
  ): ClientUnaryCall;
  validateDevice(
    request: ValidateDeviceRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ValidateDeviceResponse) => void,
  ): ClientUnaryCall;
  validateDevice(
    request: ValidateDeviceRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ValidateDeviceResponse) => void,
  ): ClientUnaryCall;
  /** Report security incident */
  reportIncident(
    request: ReportIncidentRequest,
    callback: (error: ServiceError | null, response: ReportIncidentResponse) => void,
  ): ClientUnaryCall;
  reportIncident(
    request: ReportIncidentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ReportIncidentResponse) => void,
  ): ClientUnaryCall;
  reportIncident(
    request: ReportIncidentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ReportIncidentResponse) => void,
  ): ClientUnaryCall;
  /** Get IP reputation details */
  getIpReputation(
    request: GetIPReputationRequest,
    callback: (error: ServiceError | null, response: GetIPReputationResponse) => void,
  ): ClientUnaryCall;
  getIpReputation(
    request: GetIPReputationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetIPReputationResponse) => void,
  ): ClientUnaryCall;
  getIpReputation(
    request: GetIPReputationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetIPReputationResponse) => void,
  ): ClientUnaryCall;
}

export const SecurityServiceClient = makeGenericClientConstructor(
  SecurityServiceService,
  "security.SecurityService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SecurityServiceClient;
  service: typeof SecurityServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
